// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					CiscoInterfaceAdminStatus: CiscoInterfaceAdminStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceAdminStatusMetricAttributeKey{CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceSpeed},
					},
					CiscoInterfaceCounter: CiscoInterfaceCounterMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceCounterMetricAttributeKey{CiscoInterfaceCounterMetricAttributeKeyCiscoInterfaceCounterName, CiscoInterfaceCounterMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceCounterMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceCounterMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceCounterMetricAttributeKeyNetworkInterfaceSpeed},
					},
					CiscoInterfaceErrdisabled: CiscoInterfaceErrdisabledMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceErrdisabledMetricAttributeKey{CiscoInterfaceErrdisabledMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceErrdisabledMetricAttributeKeyCiscoErrdisabledReason},
					},
					CiscoInterfaceIoRate: CiscoInterfaceIoRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceIoRateMetricAttributeKey{CiscoInterfaceIoRateMetricAttributeKeyNetworkIoDirection, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceSpeed},
					},
					CiscoInterfacePacketRate: CiscoInterfacePacketRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfacePacketRateMetricAttributeKey{CiscoInterfacePacketRateMetricAttributeKeyNetworkIoDirection, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceMac, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceName, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceSpeed},
					},
					CiscoInterfacePauseFrames: CiscoInterfacePauseFramesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfacePauseFramesMetricAttributeKey{CiscoInterfacePauseFramesMetricAttributeKeyNetworkInterfaceName, CiscoInterfacePauseFramesMetricAttributeKeyNetworkIoDirection, CiscoInterfacePauseFramesMetricAttributeKeyCiscoPauseType, CiscoInterfacePauseFramesMetricAttributeKeyCiscoQosPriority},
					},
					CiscoInterfaceQosPolicyBytes: CiscoInterfaceQosPolicyBytesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceQosPolicyBytesMetricAttributeKey{CiscoInterfaceQosPolicyBytesMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceQosPolicyBytesMetricAttributeKeyNetworkIoDirection, CiscoInterfaceQosPolicyBytesMetricAttributeKeyCiscoQosClass, CiscoInterfaceQosPolicyBytesMetricAttributeKeyCiscoQosAction, CiscoInterfaceQosPolicyBytesMetricAttributeKeyCiscoQosDropReason, CiscoInterfaceQosPolicyBytesMetricAttributeKeyCiscoQosSource},
					},
					CiscoInterfaceQosPolicyPackets: CiscoInterfaceQosPolicyPacketsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceQosPolicyPacketsMetricAttributeKey{CiscoInterfaceQosPolicyPacketsMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyNetworkIoDirection, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyCiscoQosClass, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyCiscoQosAction, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyCiscoQosDropReason, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyCiscoQosSource},
					},
					CiscoInterfaceQosQueueBytes: CiscoInterfaceQosQueueBytesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceQosQueueBytesMetricAttributeKey{CiscoInterfaceQosQueueBytesMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceQosQueueBytesMetricAttributeKeyNetworkIoDirection, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosQueue, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosGroup, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosAction, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosDropReason, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosSource},
					},
					CiscoInterfaceQosQueuePackets: CiscoInterfaceQosQueuePacketsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceQosQueuePacketsMetricAttributeKey{CiscoInterfaceQosQueuePacketsMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceQosQueuePacketsMetricAttributeKeyNetworkIoDirection, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosQueue, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosGroup, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosAction, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosDropReason, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosSource},
					},
					CiscoInterfaceSpeed: CiscoInterfaceSpeedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceSpeedMetricAttributeKey{CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfaceUtilization: CiscoInterfaceUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceUtilizationMetricAttributeKey{CiscoInterfaceUtilizationMetricAttributeKeyNetworkIoDirection, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoL2StpBlockedPorts: CiscoL2StpBlockedPortsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoL2StpBlockedPortsMetricAttributeKey{CiscoL2StpBlockedPortsMetricAttributeKeyCiscoL2Vlan, CiscoL2StpBlockedPortsMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoL2StpInstances: CiscoL2StpInstancesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoL2StpInstancesMetricAttributeKey{CiscoL2StpInstancesMetricAttributeKeyCiscoL2StpState},
					},
					CiscoL2StpTopologyChanges: CiscoL2StpTopologyChangesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoL2StpTopologyChangesMetricAttributeKey{CiscoL2StpTopologyChangesMetricAttributeKeyCiscoL2Vlan, CiscoL2StpTopologyChangesMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoLacpErrors: CiscoLacpErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoLacpErrorsMetricAttributeKey{CiscoLacpErrorsMetricAttributeKeyNetworkInterfaceName, CiscoLacpErrorsMetricAttributeKeyCiscoLacpErrorType},
					},
					CiscoLacpPackets: CiscoLacpPacketsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoLacpPacketsMetricAttributeKey{CiscoLacpPacketsMetricAttributeKeyNetworkInterfaceName, CiscoLacpPacketsMetricAttributeKeyCiscoLacpPacketType, CiscoLacpPacketsMetricAttributeKeyNetworkIoDirection},
					},
					CiscoPortChannelMemberStatus: CiscoPortChannelMemberStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoPortChannelMemberStatusMetricAttributeKey{CiscoPortChannelMemberStatusMetricAttributeKeyCiscoPortChannelName, CiscoPortChannelMemberStatusMetricAttributeKeyNetworkInterfaceName, CiscoPortChannelMemberStatusMetricAttributeKeyCiscoPortChannelState},
					},
					CiscoPortChannelStatus: CiscoPortChannelStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoPortChannelStatusMetricAttributeKey{CiscoPortChannelStatusMetricAttributeKeyCiscoPortChannelName, CiscoPortChannelStatusMetricAttributeKeyCiscoPortChannelState},
					},
					CiscoScrapeCommandDuration: CiscoScrapeCommandDurationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoScrapeCommandDurationMetricAttributeKey{CiscoScrapeCommandDurationMetricAttributeKeyCiscoScrapeCommandFamily, CiscoScrapeCommandDurationMetricAttributeKeyCiscoScrapeCommandOutcome},
					},
					CiscoScrapeCommandErrors: CiscoScrapeCommandErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoScrapeCommandErrorsMetricAttributeKey{CiscoScrapeCommandErrorsMetricAttributeKeyCiscoScrapeCommandFamily, CiscoScrapeCommandErrorsMetricAttributeKeyCiscoScrapeErrorType},
					},
					CiscoScrapePartialSuccess: CiscoScrapePartialSuccessMetricConfig{
						Enabled: true,
					},
					CiscoSSHReconnects: CiscoSSHReconnectsMetricConfig{
						Enabled: true,
					},
					CiscoTopologyNeighborInfo: CiscoTopologyNeighborInfoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoTopologyNeighborInfoMetricAttributeKey{CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyProtocol, CiscoTopologyNeighborInfoMetricAttributeKeyNetworkInterfaceName, CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyNeighborName, CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyNeighborInterface, CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyNeighborPlatform, CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyNeighborAddress},
					},
					CiscoTransceiverSensor: CiscoTransceiverSensorMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoTransceiverSensorMetricAttributeKey{CiscoTransceiverSensorMetricAttributeKeyNetworkInterfaceName, CiscoTransceiverSensorMetricAttributeKeyCiscoTransceiverSensor, CiscoTransceiverSensorMetricAttributeKeyCiscoTransceiverLane, CiscoTransceiverSensorMetricAttributeKeyCiscoTransceiverSensorUnit},
					},
					CiscoVpcConsistencyFailures: CiscoVpcConsistencyFailuresMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoVpcConsistencyFailuresMetricAttributeKey{CiscoVpcConsistencyFailuresMetricAttributeKeyCiscoVpcCheck},
					},
					CiscoVpcStatus: CiscoVpcStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoVpcStatusMetricAttributeKey{CiscoVpcStatusMetricAttributeKeyCiscoVpcDomain, CiscoVpcStatusMetricAttributeKeyCiscoVpcPeer, CiscoVpcStatusMetricAttributeKeyCiscoVpcState},
					},
					SystemNetworkErrors: SystemNetworkErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkErrorsMetricAttributeKey{SystemNetworkErrorsMetricAttributeKeyNetworkIoDirection, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceMac, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceName, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceSpeed},
					},
					SystemNetworkInterfaceStatus: SystemNetworkInterfaceStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemNetworkInterfaceStatusMetricAttributeKey{SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceMac, SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceName, SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceSpeed},
					},
					SystemNetworkIo: SystemNetworkIoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkIoMetricAttributeKey{SystemNetworkIoMetricAttributeKeyNetworkIoDirection, SystemNetworkIoMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkIoMetricAttributeKeyNetworkInterfaceMac, SystemNetworkIoMetricAttributeKeyNetworkInterfaceName, SystemNetworkIoMetricAttributeKeyNetworkInterfaceSpeed},
					},
					SystemNetworkPacketCount: SystemNetworkPacketCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkPacketCountMetricAttributeKey{SystemNetworkPacketCountMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketCountMetricAttributeKeyNetworkPacketType, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceMac, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceName, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceSpeed},
					},
					SystemNetworkPacketDropped: SystemNetworkPacketDroppedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkPacketDroppedMetricAttributeKey{SystemNetworkPacketDroppedMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceMac, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceName, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceSpeed},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostID:    ResourceAttributeConfig{Enabled: true},
					HostIP:    ResourceAttributeConfig{Enabled: true},
					HostName:  ResourceAttributeConfig{Enabled: true},
					HostType:  ResourceAttributeConfig{Enabled: true},
					HwType:    ResourceAttributeConfig{Enabled: true},
					OsName:    ResourceAttributeConfig{Enabled: true},
					OsVersion: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					CiscoInterfaceAdminStatus: CiscoInterfaceAdminStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceAdminStatusMetricAttributeKey{CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceSpeed},
					},
					CiscoInterfaceCounter: CiscoInterfaceCounterMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceCounterMetricAttributeKey{CiscoInterfaceCounterMetricAttributeKeyCiscoInterfaceCounterName, CiscoInterfaceCounterMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceCounterMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceCounterMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceCounterMetricAttributeKeyNetworkInterfaceSpeed},
					},
					CiscoInterfaceErrdisabled: CiscoInterfaceErrdisabledMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceErrdisabledMetricAttributeKey{CiscoInterfaceErrdisabledMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceErrdisabledMetricAttributeKeyCiscoErrdisabledReason},
					},
					CiscoInterfaceIoRate: CiscoInterfaceIoRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceIoRateMetricAttributeKey{CiscoInterfaceIoRateMetricAttributeKeyNetworkIoDirection, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceSpeed},
					},
					CiscoInterfacePacketRate: CiscoInterfacePacketRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfacePacketRateMetricAttributeKey{CiscoInterfacePacketRateMetricAttributeKeyNetworkIoDirection, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceMac, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceName, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceSpeed},
					},
					CiscoInterfacePauseFrames: CiscoInterfacePauseFramesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfacePauseFramesMetricAttributeKey{CiscoInterfacePauseFramesMetricAttributeKeyNetworkInterfaceName, CiscoInterfacePauseFramesMetricAttributeKeyNetworkIoDirection, CiscoInterfacePauseFramesMetricAttributeKeyCiscoPauseType, CiscoInterfacePauseFramesMetricAttributeKeyCiscoQosPriority},
					},
					CiscoInterfaceQosPolicyBytes: CiscoInterfaceQosPolicyBytesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceQosPolicyBytesMetricAttributeKey{CiscoInterfaceQosPolicyBytesMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceQosPolicyBytesMetricAttributeKeyNetworkIoDirection, CiscoInterfaceQosPolicyBytesMetricAttributeKeyCiscoQosClass, CiscoInterfaceQosPolicyBytesMetricAttributeKeyCiscoQosAction, CiscoInterfaceQosPolicyBytesMetricAttributeKeyCiscoQosDropReason, CiscoInterfaceQosPolicyBytesMetricAttributeKeyCiscoQosSource},
					},
					CiscoInterfaceQosPolicyPackets: CiscoInterfaceQosPolicyPacketsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceQosPolicyPacketsMetricAttributeKey{CiscoInterfaceQosPolicyPacketsMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyNetworkIoDirection, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyCiscoQosClass, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyCiscoQosAction, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyCiscoQosDropReason, CiscoInterfaceQosPolicyPacketsMetricAttributeKeyCiscoQosSource},
					},
					CiscoInterfaceQosQueueBytes: CiscoInterfaceQosQueueBytesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceQosQueueBytesMetricAttributeKey{CiscoInterfaceQosQueueBytesMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceQosQueueBytesMetricAttributeKeyNetworkIoDirection, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosQueue, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosGroup, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosAction, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosDropReason, CiscoInterfaceQosQueueBytesMetricAttributeKeyCiscoQosSource},
					},
					CiscoInterfaceQosQueuePackets: CiscoInterfaceQosQueuePacketsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoInterfaceQosQueuePacketsMetricAttributeKey{CiscoInterfaceQosQueuePacketsMetricAttributeKeyNetworkInterfaceName, CiscoInterfaceQosQueuePacketsMetricAttributeKeyNetworkIoDirection, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosQueue, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosGroup, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosAction, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosDropReason, CiscoInterfaceQosQueuePacketsMetricAttributeKeyCiscoQosSource},
					},
					CiscoInterfaceSpeed: CiscoInterfaceSpeedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceSpeedMetricAttributeKey{CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfaceUtilization: CiscoInterfaceUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceUtilizationMetricAttributeKey{CiscoInterfaceUtilizationMetricAttributeKeyNetworkIoDirection, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceDescription, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceMac, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoL2StpBlockedPorts: CiscoL2StpBlockedPortsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoL2StpBlockedPortsMetricAttributeKey{CiscoL2StpBlockedPortsMetricAttributeKeyCiscoL2Vlan, CiscoL2StpBlockedPortsMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoL2StpInstances: CiscoL2StpInstancesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoL2StpInstancesMetricAttributeKey{CiscoL2StpInstancesMetricAttributeKeyCiscoL2StpState},
					},
					CiscoL2StpTopologyChanges: CiscoL2StpTopologyChangesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoL2StpTopologyChangesMetricAttributeKey{CiscoL2StpTopologyChangesMetricAttributeKeyCiscoL2Vlan, CiscoL2StpTopologyChangesMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoLacpErrors: CiscoLacpErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoLacpErrorsMetricAttributeKey{CiscoLacpErrorsMetricAttributeKeyNetworkInterfaceName, CiscoLacpErrorsMetricAttributeKeyCiscoLacpErrorType},
					},
					CiscoLacpPackets: CiscoLacpPacketsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoLacpPacketsMetricAttributeKey{CiscoLacpPacketsMetricAttributeKeyNetworkInterfaceName, CiscoLacpPacketsMetricAttributeKeyCiscoLacpPacketType, CiscoLacpPacketsMetricAttributeKeyNetworkIoDirection},
					},
					CiscoPortChannelMemberStatus: CiscoPortChannelMemberStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoPortChannelMemberStatusMetricAttributeKey{CiscoPortChannelMemberStatusMetricAttributeKeyCiscoPortChannelName, CiscoPortChannelMemberStatusMetricAttributeKeyNetworkInterfaceName, CiscoPortChannelMemberStatusMetricAttributeKeyCiscoPortChannelState},
					},
					CiscoPortChannelStatus: CiscoPortChannelStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoPortChannelStatusMetricAttributeKey{CiscoPortChannelStatusMetricAttributeKeyCiscoPortChannelName, CiscoPortChannelStatusMetricAttributeKeyCiscoPortChannelState},
					},
					CiscoScrapeCommandDuration: CiscoScrapeCommandDurationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoScrapeCommandDurationMetricAttributeKey{CiscoScrapeCommandDurationMetricAttributeKeyCiscoScrapeCommandFamily, CiscoScrapeCommandDurationMetricAttributeKeyCiscoScrapeCommandOutcome},
					},
					CiscoScrapeCommandErrors: CiscoScrapeCommandErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoScrapeCommandErrorsMetricAttributeKey{CiscoScrapeCommandErrorsMetricAttributeKeyCiscoScrapeCommandFamily, CiscoScrapeCommandErrorsMetricAttributeKeyCiscoScrapeErrorType},
					},
					CiscoScrapePartialSuccess: CiscoScrapePartialSuccessMetricConfig{
						Enabled: false,
					},
					CiscoSSHReconnects: CiscoSSHReconnectsMetricConfig{
						Enabled: false,
					},
					CiscoTopologyNeighborInfo: CiscoTopologyNeighborInfoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoTopologyNeighborInfoMetricAttributeKey{CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyProtocol, CiscoTopologyNeighborInfoMetricAttributeKeyNetworkInterfaceName, CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyNeighborName, CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyNeighborInterface, CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyNeighborPlatform, CiscoTopologyNeighborInfoMetricAttributeKeyCiscoTopologyNeighborAddress},
					},
					CiscoTransceiverSensor: CiscoTransceiverSensorMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoTransceiverSensorMetricAttributeKey{CiscoTransceiverSensorMetricAttributeKeyNetworkInterfaceName, CiscoTransceiverSensorMetricAttributeKeyCiscoTransceiverSensor, CiscoTransceiverSensorMetricAttributeKeyCiscoTransceiverLane, CiscoTransceiverSensorMetricAttributeKeyCiscoTransceiverSensorUnit},
					},
					CiscoVpcConsistencyFailures: CiscoVpcConsistencyFailuresMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoVpcConsistencyFailuresMetricAttributeKey{CiscoVpcConsistencyFailuresMetricAttributeKeyCiscoVpcCheck},
					},
					CiscoVpcStatus: CiscoVpcStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoVpcStatusMetricAttributeKey{CiscoVpcStatusMetricAttributeKeyCiscoVpcDomain, CiscoVpcStatusMetricAttributeKeyCiscoVpcPeer, CiscoVpcStatusMetricAttributeKeyCiscoVpcState},
					},
					SystemNetworkErrors: SystemNetworkErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkErrorsMetricAttributeKey{SystemNetworkErrorsMetricAttributeKeyNetworkIoDirection, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceMac, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceName, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceSpeed},
					},
					SystemNetworkInterfaceStatus: SystemNetworkInterfaceStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemNetworkInterfaceStatusMetricAttributeKey{SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceMac, SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceName, SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceSpeed},
					},
					SystemNetworkIo: SystemNetworkIoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkIoMetricAttributeKey{SystemNetworkIoMetricAttributeKeyNetworkIoDirection, SystemNetworkIoMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkIoMetricAttributeKeyNetworkInterfaceMac, SystemNetworkIoMetricAttributeKeyNetworkInterfaceName, SystemNetworkIoMetricAttributeKeyNetworkInterfaceSpeed},
					},
					SystemNetworkPacketCount: SystemNetworkPacketCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkPacketCountMetricAttributeKey{SystemNetworkPacketCountMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketCountMetricAttributeKeyNetworkPacketType, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceMac, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceName, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceSpeed},
					},
					SystemNetworkPacketDropped: SystemNetworkPacketDroppedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkPacketDroppedMetricAttributeKey{SystemNetworkPacketDroppedMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceDescription, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceMac, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceName, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceSpeed},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostID:    ResourceAttributeConfig{Enabled: false},
					HostIP:    ResourceAttributeConfig{Enabled: false},
					HostName:  ResourceAttributeConfig{Enabled: false},
					HostType:  ResourceAttributeConfig{Enabled: false},
					HwType:    ResourceAttributeConfig{Enabled: false},
					OsName:    ResourceAttributeConfig{Enabled: false},
					OsVersion: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(CiscoInterfaceAdminStatusMetricConfig{}, CiscoInterfaceCounterMetricConfig{}, CiscoInterfaceErrdisabledMetricConfig{}, CiscoInterfaceIoRateMetricConfig{}, CiscoInterfacePacketRateMetricConfig{}, CiscoInterfacePauseFramesMetricConfig{}, CiscoInterfaceQosPolicyBytesMetricConfig{}, CiscoInterfaceQosPolicyPacketsMetricConfig{}, CiscoInterfaceQosQueueBytesMetricConfig{}, CiscoInterfaceQosQueuePacketsMetricConfig{}, CiscoInterfaceSpeedMetricConfig{}, CiscoInterfaceUtilizationMetricConfig{}, CiscoL2StpBlockedPortsMetricConfig{}, CiscoL2StpInstancesMetricConfig{}, CiscoL2StpTopologyChangesMetricConfig{}, CiscoLacpErrorsMetricConfig{}, CiscoLacpPacketsMetricConfig{}, CiscoPortChannelMemberStatusMetricConfig{}, CiscoPortChannelStatusMetricConfig{}, CiscoScrapeCommandDurationMetricConfig{}, CiscoScrapeCommandErrorsMetricConfig{}, CiscoScrapePartialSuccessMetricConfig{}, CiscoSSHReconnectsMetricConfig{}, CiscoTopologyNeighborInfoMetricConfig{}, CiscoTransceiverSensorMetricConfig{}, CiscoVpcConsistencyFailuresMetricConfig{}, CiscoVpcStatusMetricConfig{}, SystemNetworkErrorsMetricConfig{}, SystemNetworkInterfaceStatusMetricConfig{}, SystemNetworkIoMetricConfig{}, SystemNetworkPacketCountMetricConfig{}, SystemNetworkPacketDroppedMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestSystemNetworkErrorsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkErrors
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkErrorsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.errors doesn't have an attribute invalid, valid attributes: [network.io.direction, network.interface.description, network.interface.mac, network.interface.name, network.interface.speed]")

	cfg = DefaultMetricsConfig().SystemNetworkErrors
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSystemNetworkInterfaceStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkInterfaceStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkInterfaceStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.interface.status doesn't have an attribute invalid, valid attributes: [network.interface.description, network.interface.mac, network.interface.name, network.interface.speed]")

	cfg = DefaultMetricsConfig().SystemNetworkInterfaceStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSystemNetworkIoMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkIo
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkIoMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.io doesn't have an attribute invalid, valid attributes: [network.io.direction, network.interface.description, network.interface.mac, network.interface.name, network.interface.speed]")

	cfg = DefaultMetricsConfig().SystemNetworkIo
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSystemNetworkPacketCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkPacketCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkPacketCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.packet.count doesn't have an attribute invalid, valid attributes: [network.packet.type, network.interface.description, network.interface.mac, network.interface.name, network.interface.speed]")

	cfg = DefaultMetricsConfig().SystemNetworkPacketCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSystemNetworkPacketDroppedMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkPacketDropped
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkPacketDroppedMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.packet.dropped doesn't have an attribute invalid, valid attributes: [network.io.direction, network.interface.description, network.interface.mac, network.interface.name, network.interface.speed]")

	cfg = DefaultMetricsConfig().SystemNetworkPacketDropped
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				HostID:    ResourceAttributeConfig{Enabled: true},
				HostIP:    ResourceAttributeConfig{Enabled: true},
				HostName:  ResourceAttributeConfig{Enabled: true},
				HostType:  ResourceAttributeConfig{Enabled: true},
				HwType:    ResourceAttributeConfig{Enabled: true},
				OsName:    ResourceAttributeConfig{Enabled: true},
				OsVersion: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				HostID:    ResourceAttributeConfig{Enabled: false},
				HostIP:    ResourceAttributeConfig{Enabled: false},
				HostName:  ResourceAttributeConfig{Enabled: false},
				HostType:  ResourceAttributeConfig{Enabled: false},
				HwType:    ResourceAttributeConfig{Enabled: false},
				OsName:    ResourceAttributeConfig{Enabled: false},
				OsVersion: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
