// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Package metricschemagen generates the runtime fixed-metric descriptor
// registry from the receiver metadata catalog.
package metricschemagen

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

type metadataDocument struct {
	Metrics map[string]metricDefinition `yaml:"metrics"`
}

type metricDefinition struct {
	Description string           `yaml:"description"`
	Unit        string           `yaml:"unit"`
	Attributes  []string         `yaml:"attributes"`
	Gauge       *gaugeDefinition `yaml:"gauge"`
	Sum         *sumDefinition   `yaml:"sum"`
}

type gaugeDefinition struct {
	ValueType string `yaml:"value_type"`
}

type sumDefinition struct {
	AggregationTemporality string `yaml:"aggregation_temporality"`
	Monotonic              bool   `yaml:"monotonic"`
	ValueType              string `yaml:"value_type"`
}

// Generate returns a gofmt-formatted runtime registry for the supplied
// metadata.yaml contents.
func Generate(metadata []byte) ([]byte, error) {
	var document metadataDocument
	if err := yaml.Unmarshal(metadata, &document); err != nil {
		return nil, fmt.Errorf("parse metric metadata: %w", err)
	}
	if len(document.Metrics) == 0 {
		return nil, errors.New("metric metadata catalog is empty")
	}

	names := make([]string, 0, len(document.Metrics))
	for name := range document.Metrics {
		names = append(names, name)
	}
	sort.Strings(names)

	var output bytes.Buffer
	output.WriteString("// Copyright The OpenTelemetry Authors\n")
	output.WriteString("// SPDX-License-Identifier: Apache-2.0\n\n")
	output.WriteString("// Code generated by internal/metricschemagen. DO NOT EDIT.\n\n")
	output.WriteString("package ciscoosreceiver\n\n")
	output.WriteString("var fixedMetricDescriptors = map[string]fixedMetricDescriptor{\n")
	for _, name := range names {
		definition := document.Metrics[name]
		if strings.TrimSpace(name) == "" {
			return nil, errors.New("metric name is empty")
		}
		if strings.TrimSpace(definition.Description) == "" {
			return nil, fmt.Errorf("metric %q has an empty description", name)
		}
		instrument, valueType, monotonic, temporality, err := metricSchema(name, definition)
		if err != nil {
			return nil, err
		}
		attributes := append([]string(nil), definition.Attributes...)
		seenAttributes := make(map[string]struct{}, len(attributes))
		for _, attribute := range attributes {
			if strings.TrimSpace(attribute) == "" {
				return nil, fmt.Errorf("metric %q has an empty attribute name", name)
			}
			if _, duplicate := seenAttributes[attribute]; duplicate {
				return nil, fmt.Errorf("metric %q repeats attribute %q", name, attribute)
			}
			seenAttributes[attribute] = struct{}{}
		}
		sort.Strings(attributes)
		fmt.Fprintf(&output, "\t%s: {\n", strconv.Quote(name))
		fmt.Fprintf(&output, "\t\tdescription: %s,\n", strconv.Quote(definition.Description))
		fmt.Fprintf(&output, "\t\tunit: %s,\n", strconv.Quote(definition.Unit))
		fmt.Fprintf(&output, "\t\tinstrument: %s,\n", instrument)
		fmt.Fprintf(&output, "\t\tvalueType: %s,\n", valueType)
		fmt.Fprintf(&output, "\t\tmonotonic: %t,\n", monotonic)
		fmt.Fprintf(&output, "\t\ttemporality: %s,\n", temporality)
		if len(attributes) > 0 {
			output.WriteString("\t\toptionalAttributes: []string{")
			for index, attribute := range attributes {
				if index > 0 {
					output.WriteString(", ")
				}
				output.WriteString(strconv.Quote(attribute))
			}
			output.WriteString("},\n")
		}
		output.WriteString("\t},\n")
	}
	output.WriteString("}\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated metric schema: %w", err)
	}
	return formatted, nil
}

func metricSchema(name string, definition metricDefinition) (instrument, valueType string, monotonic bool, temporality string, err error) {
	switch {
	case definition.Gauge != nil && definition.Sum == nil:
		instrument = "fixedMetricInstrumentGauge"
		valueType, err = generatedValueType(name, definition.Gauge.ValueType)
		temporality = "fixedMetricTemporalityUnspecified"
	case definition.Gauge == nil && definition.Sum != nil:
		instrument = "fixedMetricInstrumentSum"
		valueType, err = generatedValueType(name, definition.Sum.ValueType)
		monotonic = definition.Sum.Monotonic
		if !definition.Sum.Monotonic {
			return "", "", false, "", fmt.Errorf("metric %q has a non-monotonic fixed sum", name)
		}
		if definition.Sum.AggregationTemporality != "cumulative" {
			return "", "", false, "", fmt.Errorf("metric %q has unsupported sum temporality %q", name, definition.Sum.AggregationTemporality)
		}
		temporality = "fixedMetricTemporalityCumulative"
	default:
		return "", "", false, "", fmt.Errorf("metric %q must define exactly one gauge or sum instrument", name)
	}
	if err != nil {
		return "", "", false, "", err
	}
	return instrument, valueType, monotonic, temporality, nil
}

func generatedValueType(name, valueType string) (string, error) {
	switch valueType {
	case "int":
		return "fixedMetricValueTypeInt", nil
	case "double":
		return "fixedMetricValueTypeDouble", nil
	default:
		return "", fmt.Errorf("metric %q has unsupported value type %q", name, valueType)
	}
}
