// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/collector/receiver"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"
)

func NewSettings(tt *componenttest.Telemetry) receiver.Settings {
	set := receivertest.NewNopSettings(receivertest.NopType)
	set.ID = component.NewID(component.MustNewType("cisco_os"))
	set.TelemetrySettings = tt.NewTelemetrySettings()
	return set
}

func AssertEqualCiscoosreceiverGnmiAuthenticationFailures(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_authentication_failures",
		Description: "Number of gNMI authentication or authorization failures [Development]",
		Unit:        "{failure}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_authentication_failures")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiCacheUtilization(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[float64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_cache_utilization",
		Description: "Fraction of the configured mapped-series cache currently in use [Development]",
		Unit:        "1",
		Data: metricdata.Gauge[float64]{
			DataPoints: dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_cache_utilization")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiConnections(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_connections",
		Description: "Current number of established gNMI connections [Development]",
		Unit:        "{connection}",
		Data: metricdata.Gauge[int64]{
			DataPoints: dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_connections")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiConsumerRefusals(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_consumer_refusals",
		Description: "Number of metric chunks refused by the downstream consumer and dropped without device reconnect [Development]",
		Unit:        "{refusal}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_consumer_refusals")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiDecodeErrors(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_decode_errors",
		Description: "Number of gNMI notifications that could not be decoded [Development]",
		Unit:        "{error}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_decode_errors")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiDeletes(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_deletes",
		Description: "Number of gNMI delete paths applied to the state cache [Development]",
		Unit:        "{delete}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_deletes")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiDuplicateUpdates(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_duplicate_updates",
		Description: "Number of duplicate gNMI leaf updates suppressed by the state cache [Development]",
		Unit:        "{update}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_duplicate_updates")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiInvalidTimestamps(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_invalid_timestamps",
		Description: "Number of invalid Cisco timestamps replaced with receipt time [Development]",
		Unit:        "{timestamp}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_invalid_timestamps")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiLastSuccessUnixtime(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_last_success_unixtime",
		Description: "Unix time of the most recent successfully decoded gNMI notification [Development]",
		Unit:        "s",
		Data: metricdata.Gauge[int64]{
			DataPoints: dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_last_success_unixtime")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiProfileDegraded(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_profile_degraded",
		Description: "Whether a gNMI profile is degraded (1 = degraded, 0 = healthy) [Development]",
		Unit:        "1",
		Data: metricdata.Gauge[int64]{
			DataPoints: dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_profile_degraded")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiReconnects(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_reconnects",
		Description: "Number of gNMI transport reconnect attempts [Development]",
		Unit:        "{reconnect}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_reconnects")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiSubscriptions(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_subscriptions",
		Description: "Current number of active gNMI subscription streams [Development]",
		Unit:        "{subscription}",
		Data: metricdata.Gauge[int64]{
			DataPoints: dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_subscriptions")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiUnmappedValues(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_unmapped_values",
		Description: "Number of decoded gNMI values without an explicit metric mapping [Development]",
		Unit:        "{value}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_unmapped_values")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}

func AssertEqualCiscoosreceiverGnmiUpdates(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_ciscoosreceiver_gnmi_updates",
		Description: "Number of decoded gNMI leaf updates [Development]",
		Unit:        "{update}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_ciscoosreceiver_gnmi_updates")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}
