// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/ciscoosreceiver/internal/metadata"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.CiscoosreceiverGnmiAuthenticationFailures.Add(context.Background(), 1)
	tb.CiscoosreceiverGnmiCacheUtilization.Record(context.Background(), 1)
	tb.CiscoosreceiverGnmiConnections.Record(context.Background(), 1)
	tb.CiscoosreceiverGnmiConsumerRefusals.Add(context.Background(), 1)
	tb.CiscoosreceiverGnmiDecodeErrors.Add(context.Background(), 1)
	tb.CiscoosreceiverGnmiDeletes.Add(context.Background(), 1)
	tb.CiscoosreceiverGnmiDuplicateUpdates.Add(context.Background(), 1)
	tb.CiscoosreceiverGnmiInvalidTimestamps.Add(context.Background(), 1)
	tb.CiscoosreceiverGnmiLastSuccessUnixtime.Record(context.Background(), 1)
	tb.CiscoosreceiverGnmiProfileDegraded.Record(context.Background(), 1)
	tb.CiscoosreceiverGnmiReconnects.Add(context.Background(), 1)
	tb.CiscoosreceiverGnmiSubscriptions.Record(context.Background(), 1)
	tb.CiscoosreceiverGnmiUnmappedValues.Add(context.Background(), 1)
	tb.CiscoosreceiverGnmiUpdates.Add(context.Background(), 1)
	AssertEqualCiscoosreceiverGnmiAuthenticationFailures(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiCacheUtilization(t, testTel,
		[]metricdata.DataPoint[float64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiConnections(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiConsumerRefusals(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiDecodeErrors(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiDeletes(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiDuplicateUpdates(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiInvalidTimestamps(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiLastSuccessUnixtime(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiProfileDegraded(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiReconnects(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiSubscriptions(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiUnmappedValues(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualCiscoosreceiverGnmiUpdates(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
