// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["kvm.domain.disk.errors"] = mb.metricKvmDomainDiskErrors.config.AggregationStrategy
			aggMap["kvm.domain.disk.read.bytes"] = mb.metricKvmDomainDiskReadBytes.config.AggregationStrategy
			aggMap["kvm.domain.disk.read.operations"] = mb.metricKvmDomainDiskReadOperations.config.AggregationStrategy
			aggMap["kvm.domain.disk.write.bytes"] = mb.metricKvmDomainDiskWriteBytes.config.AggregationStrategy
			aggMap["kvm.domain.disk.write.operations"] = mb.metricKvmDomainDiskWriteOperations.config.AggregationStrategy
			aggMap["kvm.domain.network.receive.bytes"] = mb.metricKvmDomainNetworkReceiveBytes.config.AggregationStrategy
			aggMap["kvm.domain.network.receive.drops"] = mb.metricKvmDomainNetworkReceiveDrops.config.AggregationStrategy
			aggMap["kvm.domain.network.receive.errors"] = mb.metricKvmDomainNetworkReceiveErrors.config.AggregationStrategy
			aggMap["kvm.domain.network.receive.packets"] = mb.metricKvmDomainNetworkReceivePackets.config.AggregationStrategy
			aggMap["kvm.domain.network.transmit.bytes"] = mb.metricKvmDomainNetworkTransmitBytes.config.AggregationStrategy
			aggMap["kvm.domain.network.transmit.drops"] = mb.metricKvmDomainNetworkTransmitDrops.config.AggregationStrategy
			aggMap["kvm.domain.network.transmit.errors"] = mb.metricKvmDomainNetworkTransmitErrors.config.AggregationStrategy
			aggMap["kvm.domain.network.transmit.packets"] = mb.metricKvmDomainNetworkTransmitPackets.config.AggregationStrategy
			aggMap["kvm.domain.state"] = mb.metricKvmDomainState.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainCPUCountDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainCPUTimeDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainDiskErrorsDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainDiskErrorsDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainDiskReadBytesDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainDiskReadBytesDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainDiskReadOperationsDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainDiskReadOperationsDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainDiskWriteBytesDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainDiskWriteBytesDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainDiskWriteOperationsDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainDiskWriteOperationsDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainMemoryCurrentDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainMemoryMaximumDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainNetworkReceiveBytesDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainNetworkReceiveBytesDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainNetworkReceiveDropsDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainNetworkReceiveDropsDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainNetworkReceiveErrorsDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainNetworkReceiveErrorsDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainNetworkReceivePacketsDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainNetworkReceivePacketsDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainNetworkTransmitBytesDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainNetworkTransmitBytesDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainNetworkTransmitDropsDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainNetworkTransmitDropsDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainNetworkTransmitErrorsDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainNetworkTransmitErrorsDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainNetworkTransmitPacketsDataPoint(ts, 1, "device-val")
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainNetworkTransmitPacketsDataPoint(ts, 3, "device-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKvmDomainStateDataPoint(ts, 1, AttributeStateNostate)
			if tt.name == "reaggregate_set" {
				mb.RecordKvmDomainStateDataPoint(ts, 3, AttributeStateRunning)
			}

			rb := mb.NewResourceBuilder()
			rb.SetKvmDomainName("kvm.domain.name-val")
			rb.SetKvmDomainUUID("kvm.domain.uuid-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricKvmDomainDiskErrors.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainDiskReadBytes.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainDiskReadOperations.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainDiskWriteBytes.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainDiskWriteOperations.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainNetworkReceiveBytes.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainNetworkReceiveDrops.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainNetworkReceiveErrors.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainNetworkReceivePackets.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainNetworkTransmitBytes.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainNetworkTransmitDrops.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainNetworkTransmitErrors.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainNetworkTransmitPackets.aggDataPoints)
				assert.Empty(t, mb.metricKvmDomainState.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "kvm.domain.cpu.count":
					assert.False(t, validatedMetrics["kvm.domain.cpu.count"], "Found a duplicate in the metrics slice: kvm.domain.cpu.count")
					validatedMetrics["kvm.domain.cpu.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of virtual CPUs currently configured for the domain.", mi.Description())
					assert.Equal(t, "{cpu}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "kvm.domain.cpu.time":
					assert.False(t, validatedMetrics["kvm.domain.cpu.time"], "Found a duplicate in the metrics slice: kvm.domain.cpu.time")
					validatedMetrics["kvm.domain.cpu.time"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total CPU time consumed by the domain.", mi.Description())
					assert.Equal(t, "ns", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "kvm.domain.disk.errors":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.disk.errors"], "Found a duplicate in the metrics slice: kvm.domain.disk.errors")
						validatedMetrics["kvm.domain.disk.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total disk I/O errors reported for the domain disk device.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.disk.errors"], "Found a duplicate in the metrics slice: kvm.domain.disk.errors")
						validatedMetrics["kvm.domain.disk.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total disk I/O errors reported for the domain disk device.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.disk.errors"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.disk.read.bytes":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.disk.read.bytes"], "Found a duplicate in the metrics slice: kvm.domain.disk.read.bytes")
						validatedMetrics["kvm.domain.disk.read.bytes"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total bytes read by the domain disk device.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.disk.read.bytes"], "Found a duplicate in the metrics slice: kvm.domain.disk.read.bytes")
						validatedMetrics["kvm.domain.disk.read.bytes"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total bytes read by the domain disk device.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.disk.read.bytes"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.disk.read.operations":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.disk.read.operations"], "Found a duplicate in the metrics slice: kvm.domain.disk.read.operations")
						validatedMetrics["kvm.domain.disk.read.operations"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total read operations issued to the domain disk device.", mi.Description())
						assert.Equal(t, "{operation}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.disk.read.operations"], "Found a duplicate in the metrics slice: kvm.domain.disk.read.operations")
						validatedMetrics["kvm.domain.disk.read.operations"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total read operations issued to the domain disk device.", mi.Description())
						assert.Equal(t, "{operation}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.disk.read.operations"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.disk.write.bytes":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.disk.write.bytes"], "Found a duplicate in the metrics slice: kvm.domain.disk.write.bytes")
						validatedMetrics["kvm.domain.disk.write.bytes"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total bytes written by the domain disk device.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.disk.write.bytes"], "Found a duplicate in the metrics slice: kvm.domain.disk.write.bytes")
						validatedMetrics["kvm.domain.disk.write.bytes"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total bytes written by the domain disk device.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.disk.write.bytes"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.disk.write.operations":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.disk.write.operations"], "Found a duplicate in the metrics slice: kvm.domain.disk.write.operations")
						validatedMetrics["kvm.domain.disk.write.operations"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total write operations issued to the domain disk device.", mi.Description())
						assert.Equal(t, "{operation}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.disk.write.operations"], "Found a duplicate in the metrics slice: kvm.domain.disk.write.operations")
						validatedMetrics["kvm.domain.disk.write.operations"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total write operations issued to the domain disk device.", mi.Description())
						assert.Equal(t, "{operation}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.disk.write.operations"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.memory.current":
					assert.False(t, validatedMetrics["kvm.domain.memory.current"], "Found a duplicate in the metrics slice: kvm.domain.memory.current")
					validatedMetrics["kvm.domain.memory.current"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Current memory assigned to the domain.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "kvm.domain.memory.maximum":
					assert.False(t, validatedMetrics["kvm.domain.memory.maximum"], "Found a duplicate in the metrics slice: kvm.domain.memory.maximum")
					validatedMetrics["kvm.domain.memory.maximum"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Maximum memory configured for the domain.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "kvm.domain.network.receive.bytes":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.network.receive.bytes"], "Found a duplicate in the metrics slice: kvm.domain.network.receive.bytes")
						validatedMetrics["kvm.domain.network.receive.bytes"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total bytes received by the domain network interface.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.network.receive.bytes"], "Found a duplicate in the metrics slice: kvm.domain.network.receive.bytes")
						validatedMetrics["kvm.domain.network.receive.bytes"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total bytes received by the domain network interface.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.network.receive.bytes"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.network.receive.drops":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.network.receive.drops"], "Found a duplicate in the metrics slice: kvm.domain.network.receive.drops")
						validatedMetrics["kvm.domain.network.receive.drops"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total received packets dropped for the domain network interface.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.network.receive.drops"], "Found a duplicate in the metrics slice: kvm.domain.network.receive.drops")
						validatedMetrics["kvm.domain.network.receive.drops"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total received packets dropped for the domain network interface.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.network.receive.drops"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.network.receive.errors":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.network.receive.errors"], "Found a duplicate in the metrics slice: kvm.domain.network.receive.errors")
						validatedMetrics["kvm.domain.network.receive.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total receive errors reported for the domain network interface.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.network.receive.errors"], "Found a duplicate in the metrics slice: kvm.domain.network.receive.errors")
						validatedMetrics["kvm.domain.network.receive.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total receive errors reported for the domain network interface.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.network.receive.errors"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.network.receive.packets":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.network.receive.packets"], "Found a duplicate in the metrics slice: kvm.domain.network.receive.packets")
						validatedMetrics["kvm.domain.network.receive.packets"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total packets received by the domain network interface.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.network.receive.packets"], "Found a duplicate in the metrics slice: kvm.domain.network.receive.packets")
						validatedMetrics["kvm.domain.network.receive.packets"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total packets received by the domain network interface.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.network.receive.packets"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.network.transmit.bytes":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.network.transmit.bytes"], "Found a duplicate in the metrics slice: kvm.domain.network.transmit.bytes")
						validatedMetrics["kvm.domain.network.transmit.bytes"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total bytes transmitted by the domain network interface.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.network.transmit.bytes"], "Found a duplicate in the metrics slice: kvm.domain.network.transmit.bytes")
						validatedMetrics["kvm.domain.network.transmit.bytes"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total bytes transmitted by the domain network interface.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.network.transmit.bytes"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.network.transmit.drops":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.network.transmit.drops"], "Found a duplicate in the metrics slice: kvm.domain.network.transmit.drops")
						validatedMetrics["kvm.domain.network.transmit.drops"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total transmitted packets dropped for the domain network interface.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.network.transmit.drops"], "Found a duplicate in the metrics slice: kvm.domain.network.transmit.drops")
						validatedMetrics["kvm.domain.network.transmit.drops"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total transmitted packets dropped for the domain network interface.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.network.transmit.drops"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.network.transmit.errors":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.network.transmit.errors"], "Found a duplicate in the metrics slice: kvm.domain.network.transmit.errors")
						validatedMetrics["kvm.domain.network.transmit.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total transmit errors reported for the domain network interface.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.network.transmit.errors"], "Found a duplicate in the metrics slice: kvm.domain.network.transmit.errors")
						validatedMetrics["kvm.domain.network.transmit.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total transmit errors reported for the domain network interface.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.network.transmit.errors"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.network.transmit.packets":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.network.transmit.packets"], "Found a duplicate in the metrics slice: kvm.domain.network.transmit.packets")
						validatedMetrics["kvm.domain.network.transmit.packets"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total packets transmitted by the domain network interface.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						deviceAttrVal, ok := dp.Attributes().Get("device")
						assert.True(t, ok)
						assert.Equal(t, "device-val", deviceAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.network.transmit.packets"], "Found a duplicate in the metrics slice: kvm.domain.network.transmit.packets")
						validatedMetrics["kvm.domain.network.transmit.packets"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Total packets transmitted by the domain network interface.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.network.transmit.packets"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("device")
						assert.False(t, ok)
					}
				case "kvm.domain.state":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["kvm.domain.state"], "Found a duplicate in the metrics slice: kvm.domain.state")
						validatedMetrics["kvm.domain.state"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Current state of the domain, represented as one for the state attribute.", mi.Description())
						assert.Equal(t, "{state}", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						stateAttrVal, ok := dp.Attributes().Get("state")
						assert.True(t, ok)
						assert.Equal(t, "nostate", stateAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["kvm.domain.state"], "Found a duplicate in the metrics slice: kvm.domain.state")
						validatedMetrics["kvm.domain.state"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Current state of the domain, represented as one for the state attribute.", mi.Description())
						assert.Equal(t, "{state}", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["kvm.domain.state"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("state")
						assert.False(t, ok)
					}
				}
			}
		})
	}
}
