// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package gnmicataloggen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"slices"
	"sort"
	"strconv"
	"strings"
)

type Outputs struct {
	Go       []byte
	Coverage []byte
	Metrics  []byte
}

type OutputPaths struct {
	Go       string
	Coverage string
	Metrics  string
}

func Render(catalog *Catalog) (Outputs, error) {
	goSource, err := renderGo(catalog)
	if err != nil {
		return Outputs{}, err
	}
	return Outputs{
		Go:       goSource,
		Coverage: renderCoverage(catalog),
		Metrics:  renderMetrics(catalog),
	}, nil
}

func WriteOrCheck(outputs Outputs, paths OutputPaths, check bool) error {
	artifacts := []struct {
		name string
		path string
		data []byte
	}{
		{name: "Go catalog", path: paths.Go, data: outputs.Go},
		{name: "coverage documentation", path: paths.Coverage, data: outputs.Coverage},
		{name: "metric documentation", path: paths.Metrics, data: outputs.Metrics},
	}
	for _, artifact := range artifacts {
		if artifact.path == "" {
			return fmt.Errorf("%s output path cannot be empty", artifact.name)
		}
		if check {
			existing, err := os.ReadFile(artifact.path)
			if err != nil {
				return fmt.Errorf("read generated %s: %w", artifact.name, err)
			}
			if !bytes.Equal(existing, artifact.data) {
				return fmt.Errorf("generated %s is stale: run make gnmi-catalog", artifact.name)
			}
			continue
		}
		// Generated Go and Markdown are public repository artifacts, not secrets.
		//nolint:gosec // Repository source and documentation must remain group/world-readable.
		if err := os.WriteFile(artifact.path, artifact.data, 0o644); err != nil {
			return fmt.Errorf("write generated %s: %w", artifact.name, err)
		}
	}
	return nil
}

func renderGo(catalog *Catalog) ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("// Copyright The OpenTelemetry Authors\n")
	out.WriteString("// SPDX-License-Identifier: Apache-2.0\n\n")
	out.WriteString("// Code generated by gnmicataloggen. DO NOT EDIT.\n\n")
	out.WriteString("package ciscoosreceiver\n\n")
	out.WriteString("import (\n\t\"time\"\n\n\tinternalgnmi \"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/ciscoosreceiver/internal/gnmi\"\n)\n\n")

	metricNames := referencedMetricNames(catalog)
	out.WriteString("var builtinGNMIMetricMetadata = map[string]internalgnmi.MetricMetadata{\n")
	for _, name := range metricNames {
		metric := catalog.Metadata.Metrics[name]
		fmt.Fprintf(&out, "\t%q: {Name: %q, Description: %q, Unit: %q},\n", name, name, metric.Description, metric.Unit)
	}
	out.WriteString("}\n\n")

	profiles := slices.Clone(catalog.Profiles)
	sort.Slice(profiles, func(i, j int) bool {
		if profiles[i].Platform != profiles[j].Platform {
			return profiles[i].Platform < profiles[j].Platform
		}
		return profiles[i].Name < profiles[j].Name
	})
	out.WriteString("var builtinGNMIProfileCatalog = map[string]map[string]builtinGNMIProfileDefinition{\n")
	currentPlatform := ""
	for profileIndex := range profiles {
		profile := &profiles[profileIndex]
		if profile.Platform != currentPlatform {
			if currentPlatform != "" {
				out.WriteString("\t},\n")
			}
			currentPlatform = profile.Platform
			fmt.Fprintf(&out, "\t%q: {\n", currentPlatform)
		}
		fmt.Fprintf(&out, "\t\t%q: {\n", profile.Name)
		fmt.Fprintf(&out, "\t\t\tName: %q, DefaultEnabled: %t, DefaultInterval: %s,\n", profile.Name, profile.DefaultEnabled, durationLiteral(profile.Interval))
		if len(profile.Synthetic) > 0 {
			out.WriteString("\t\t\tSyntheticMappings: []builtinGNMIMapping{\n")
			for mappingIndex := range profile.Synthetic {
				renderMapping(&out, &profile.Synthetic[mappingIndex], "\t\t\t\t")
			}
			out.WriteString("\t\t\t},\n")
		}
		if len(profile.Paths) > 0 {
			out.WriteString("\t\t\tPaths: []builtinGNMIPathDefinition{\n")
			for pathIndex := range profile.Paths {
				path := &profile.Paths[pathIndex]
				fmt.Fprintf(&out, "\t\t\t\t{ID: %q, Group: %q, PathSetID: %q, VariantID: %q, VariantOrder: %d, SourcePreference: %q, Origin: %q, Path: %q, Encodings: %#v, StreamModes: %#v, SampleInterval: %s, FeaturePrerequisites: %#v, SelectorKeys: %#v, HighCardinality: %t, RequiresMaxEntities: %t, ModelProvenance: %q, ModelRefs: %#v, Experimental: %t, Disposition: %q, Findings: %q, FixtureIDs: %#v, LiveEvidence: %#v, CLIEvidence: %#v",
					path.ID, path.Group, path.PathSetID, path.VariantID, path.VariantOrder, path.SourcePreference,
					path.Origin, path.Path.Path, path.Encodings, path.StreamModes, durationLiteral(path.Interval), path.FeaturePrerequisites,
					path.SelectorKeys, path.HighCardinality, path.RequiresMaxEntities, path.ModelProvenance, path.ModelRefs,
					path.Experimental, path.Disposition, path.Findings, path.Fixtures, path.LiveEvidence, path.CLIEvidence)
				if len(path.ListKeys) > 0 {
					out.WriteString(", JSONListKeys: []internalgnmi.JSONListKeySpec{")
					for _, spec := range path.ListKeys {
						fmt.Fprintf(&out, "{Origin: %q, Elements: %#v, Keys: %#v},", path.Origin, spec.Elements, spec.Keys)
					}
					out.WriteString("}")
				}
				if len(path.EntityJoins) > 0 {
					out.WriteString(", EntityJoins: []gnmiCatalogEntityJoinDefinition{")
					for _, join := range path.EntityJoins {
						fmt.Fprintf(&out, "{Entity: %q, Elements: %#v, Keys: %#v},", join.Entity, join.Elements, join.Keys)
					}
					out.WriteString("}")
				}
				if len(path.Mappings) == 0 {
					out.WriteString("},\n")
					continue
				}
				out.WriteString(", Mappings: []builtinGNMIMapping{\n")
				for mappingIndex := range path.Mappings {
					renderMapping(&out, &path.Mappings[mappingIndex], "\t\t\t\t\t")
				}
				out.WriteString("\t\t\t\t}},\n")
			}
			out.WriteString("\t\t\t},\n")
		}
		out.WriteString("\t\t},\n")
	}
	if currentPlatform != "" {
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n\n")

	fmt.Fprintf(&out, "const gnmiCatalogSnapshotDate = %q\n\n", catalog.Manifest.SnapshotDate)
	out.WriteString("var builtinGNMICatalogSources = []gnmiCatalogSourceDefinition{\n")
	for _, source := range catalog.Manifest.Sources {
		fmt.Fprintf(&out, "\t{ID: %q, Title: %q, URL: %q, PublishedOrUpdated: %q, Accessed: %q},\n", source.ID, source.Title, source.URL, source.PublishedOrUpdated, source.Accessed)
	}
	out.WriteString("}\n\n")
	out.WriteString("var builtinGNMICatalogDomains = []string{\n")
	for _, domain := range catalog.Manifest.Domains {
		fmt.Fprintf(&out, "\t%q,\n", domain)
	}
	out.WriteString("}\n\n")
	out.WriteString("var builtinGNMICatalogProductFamilies = []gnmiCatalogProductFamilyDefinition{\n")
	for _, family := range catalog.Manifest.ProductFamilies {
		fmt.Fprintf(&out, "\t{ID: %q, Platform: %q, MaxStreams: %d},\n", family.ID, family.Platform, family.MaxStreams)
	}
	out.WriteString("}\n\n")
	out.WriteString("var builtinGNMICatalogProducts = []gnmiCatalogProductDefinition{\n")
	for productIndex := range catalog.Manifest.Products {
		product := &catalog.Manifest.Products[productIndex]
		fmt.Fprintf(&out, "\t{ID: %q, Family: %q, PIDPatterns: %#v, ReleasePatterns: %#v, SourceIDs: %#v, RuntimeEligible: %t, Roles: %#v, ControlPlanes: %#v, OperatingModes: %#v, HardwareClasses: %#v, Findings: %q, Coverage: map[string]string{\n",
			product.ID, product.Family, product.PIDPatterns, product.ReleasePatterns, product.Sources, product.RuntimeEligible,
			product.Roles, product.ControlPlanes, product.OperatingModes, product.HardwareClasses, product.Findings)
		domains := sortedMapKeys(product.Coverage)
		for _, domain := range domains {
			fmt.Fprintf(&out, "\t\t%q: %q,\n", domain, product.Coverage[domain])
		}
		out.WriteString("\t}},\n")
	}
	out.WriteString("}\n\n")
	out.WriteString("var builtinGNMICatalogModelBundles = []gnmiCatalogModelBundleDefinition{\n")
	for _, bundle := range catalog.Manifest.ModelBundles {
		fmt.Fprintf(&out, "\t{ID: %q, Disposition: %q, Findings: %q", bundle.ID, bundle.Disposition, bundle.Findings)
		if len(bundle.Modules) > 0 {
			out.WriteString(", Modules: []gnmiCatalogModelModuleDefinition{")
			for _, module := range bundle.Modules {
				fmt.Fprintf(&out, "{ID: %q, Name: %q, Revision: %q, File: %q, SHA256: %q},", module.ID, module.Name, module.Revision, module.File, module.SHA256)
			}
			out.WriteString("}")
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n\n")
	out.WriteString("var builtinGNMICatalogFixtures = []gnmiCatalogFixtureDefinition{\n")
	for _, fixture := range catalog.Manifest.Fixtures {
		fmt.Fprintf(&out, "\t{ID: %q, File: %q, SHA256: %q},\n", fixture.ID, fixture.File, fixture.SHA256)
	}
	out.WriteString("}\n")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go catalog: %w\n%s", err, out.String())
	}
	return formatted, nil
}

func renderMapping(out *bytes.Buffer, mapping *ResolvedMapping, indent string) {
	contract := mapping.Contract
	gaugeType := "internalgnmi.GaugeInt"
	metricType := "internalgnmi.MetricGauge"
	monotonic := false
	var valueType string
	if contract.Gauge != nil {
		valueType = contract.Gauge.ValueType
	} else {
		metricType = "internalgnmi.MetricSum"
		valueType = contract.Sum.ValueType
		monotonic = contract.Sum.Monotonic
	}
	if valueType == "double" {
		gaugeType = "internalgnmi.GaugeDouble"
	}
	fmt.Fprintf(out, "%s{Mapping: internalgnmi.Mapping{Source: internalgnmi.SourcePath{Origin: %q, Elements: %#v, Leaf: %q}, Metric: builtinGNMIMetricMetadata[%q], Scale: %s, GaugeType: %s, MetricType: %s, Monotonic: %t", indent, mapping.Origin, mapping.Elements, mapping.Leaf, mapping.Metric, strconv.FormatFloat(mapping.Scale, 'g', -1, 64), gaugeType, metricType, monotonic)
	if len(mapping.Keys) > 0 {
		out.WriteString(", KeyAttributes: []internalgnmi.KeyAttribute{")
		for _, key := range mapping.Keys {
			fmt.Fprintf(out, "{Element: %q, Key: %q, Attribute: %q},", key.Element, key.Key, key.Attribute)
		}
		out.WriteString("}")
	}
	out.WriteString("}")
	if len(mapping.Attributes) > 0 {
		out.WriteString(", StaticAttributes: map[string]string{")
		for _, key := range sortedMapKeys(mapping.Attributes) {
			fmt.Fprintf(out, "%q: %q,", key, mapping.Attributes[key])
		}
		out.WriteString("}")
	}
	out.WriteString("},\n")
}

func renderCoverage(catalog *Catalog) []byte {
	var out bytes.Buffer
	out.WriteString("<!-- Code generated by gnmicataloggen. DO NOT EDIT. -->\n\n")
	out.WriteString("# Cisco gNMI Product and Domain Coverage\n\n")
	fmt.Fprintf(&out, "Catalog snapshot: `%s`. A row is shown as **Supported** only when its manifest disposition is `live_qualified`; catalog presence, fixtures, or a sibling SKU are not support evidence. `Runtime eligible` only permits an exact selector match to attempt catalog paths. A `findings` row remains an unqualified runtime candidate, even when runtime eligible is true.\n\n", catalog.Manifest.SnapshotDate)
	out.WriteString("| Product row | Family | PID selector | Release selector | Sources | Runtime eligible | Predicates | Domain | Result | Qualification evidence | Findings |\n")
	out.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for productIndex := range catalog.Manifest.Products {
		product := &catalog.Manifest.Products[productIndex]
		predicates := append([]string{}, product.Roles...)
		predicates = append(predicates, product.ControlPlanes...)
		predicates = append(predicates, product.OperatingModes...)
		predicates = append(predicates, product.HardwareClasses...)
		for _, domain := range catalog.Manifest.Domains {
			status := product.Coverage[domain]
			qualification := product.Qualifications[domain]
			evidence := append([]string{}, qualification.LiveEvidence...)
			evidence = append(evidence, qualification.CLIEvidence...)
			fmt.Fprintf(&out, "| `%s` | `%s` | `%s` | `%s` | %s | `%t` | %s | `%s` | %s | %s | %s |\n",
				markdownCell(product.ID), markdownCell(product.Family), markdownCell(strings.Join(product.PIDPatterns, ", ")),
				markdownCell(strings.Join(product.ReleasePatterns, ", ")), codeList(product.Sources), product.RuntimeEligible, codeList(predicates),
				markdownCell(domain), coverageLabel(status), codeList(evidence), markdownCell(product.Findings))
		}
	}
	out.WriteString("\n## Sources\n\n")
	for _, source := range catalog.Manifest.Sources {
		dates := "accessed " + source.Accessed
		if source.PublishedOrUpdated != "" {
			dates = "published/updated " + source.PublishedOrUpdated + "; " + dates
		}
		fmt.Fprintf(&out, "- [%s](%s) (%s)\n", source.Title, source.URL, dates)
	}
	out.WriteString("\n## Local model provenance\n\n")
	out.WriteString("Model artifacts are never downloaded by the generator. A `pending` bundle records that no local bundle was supplied; every normal generation/check accepts a `verified` bundle only after independently reading its local files and matching the recorded module name, revision, and SHA-256 digest.\n\n")
	out.WriteString("| Bundle | Disposition | Recorded modules | Findings |\n")
	out.WriteString("| --- | --- | --- | --- |\n")
	for _, bundle := range catalog.Manifest.ModelBundles {
		modules := make([]string, 0, len(bundle.Modules))
		for _, module := range bundle.Modules {
			modules = append(modules, module.Name+"@"+module.Revision+" ("+module.File+")")
		}
		fmt.Fprintf(&out, "| `%s` | `%s` | %s | %s |\n", bundle.ID, bundle.Disposition, codeList(modules), markdownCell(bundle.Findings))
	}
	return out.Bytes()
}

func renderMetrics(catalog *Catalog) []byte {
	usage := map[string][]string{}
	for profileIndex := range catalog.Profiles {
		profile := &catalog.Profiles[profileIndex]
		for mappingIndex := range profile.Synthetic {
			mapping := &profile.Synthetic[mappingIndex]
			usage[mapping.Metric] = append(usage[mapping.Metric], profile.Platform+"/"+profile.Name+" (synthetic)")
		}
		for pathIndex := range profile.Paths {
			path := &profile.Paths[pathIndex]
			for mappingIndex := range path.Mappings {
				mapping := &path.Mappings[mappingIndex]
				usage[mapping.Metric] = append(usage[mapping.Metric], profile.Platform+"/"+profile.Name+"/"+path.ID)
			}
		}
	}
	var out bytes.Buffer
	out.WriteString("<!-- Code generated by gnmicataloggen. DO NOT EDIT. -->\n\n")
	out.WriteString("# Cisco gNMI Metric Catalog\n\n")
	fmt.Fprintf(&out, "Generated from the catalog snapshot `%s` and the component `metadata.yaml`. A path with `findings` disposition is an unqualified runtime candidate, not a supported path; its missing model, fixture, or live evidence is recorded below.\n\n", catalog.Manifest.SnapshotDate)
	out.WriteString("| Metric | Type | Unit | Declared attributes | Catalog uses |\n")
	out.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, name := range referencedMetricNames(catalog) {
		metric := catalog.Metadata.Metrics[name]
		var metricType string
		if metric.Gauge != nil {
			metricType = "gauge/" + metric.Gauge.ValueType
		} else {
			metricType = "sum/" + metric.Sum.ValueType
		}
		uses := slices.Clone(usage[name])
		slices.Sort(uses)
		uses = slices.Compact(uses)
		fmt.Fprintf(&out, "| `%s` | `%s` | `%s` | %s | %s |\n", name, metricType, markdownCell(metric.Unit), codeList(metric.Attributes), codeList(uses))
	}
	out.WriteString("\n## Path evidence\n\n")
	out.WriteString("| Platform | Profile/group | Path set / variant | Source | Encodings / modes | Model provenance | Selectors / cardinality | Disposition / fixtures | Live / CLI evidence | Findings |\n")
	out.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for profileIndex := range catalog.Profiles {
		profile := &catalog.Profiles[profileIndex]
		for pathIndex := range profile.Paths {
			path := &profile.Paths[pathIndex]
			cardinality := "bounded"
			if path.HighCardinality {
				cardinality = "high; max_entities required"
			}
			fmt.Fprintf(&out, "| `%s` | `%s` / `%s` | `%s` / `%d:%s` | `%s` / `%s` | %s / %s | `%s` %s | %s / %s | `%s` / %s | %s / %s | %s |\n",
				profile.Platform, profile.Name, path.Group, path.PathSetID, path.VariantOrder, path.VariantID,
				path.SourcePreference, path.Origin, codeList(path.Encodings), codeList(path.StreamModes), path.ModelProvenance,
				codeList(path.ModelRefs), codeList(path.SelectorKeys), cardinality, path.Disposition, codeList(path.Fixtures),
				codeList(path.LiveEvidence), codeList(path.CLIEvidence), markdownCell(path.Findings))
		}
	}
	return out.Bytes()
}

func referencedMetricNames(catalog *Catalog) []string {
	set := map[string]struct{}{}
	for profileIndex := range catalog.Profiles {
		profile := &catalog.Profiles[profileIndex]
		for mappingIndex := range profile.Synthetic {
			mapping := &profile.Synthetic[mappingIndex]
			set[mapping.Metric] = struct{}{}
		}
		for pathIndex := range profile.Paths {
			path := &profile.Paths[pathIndex]
			for mappingIndex := range path.Mappings {
				mapping := &path.Mappings[mappingIndex]
				set[mapping.Metric] = struct{}{}
			}
		}
	}
	return sortedMapKeys(set)
}

func coverageLabel(status string) string {
	switch status {
	case "live_qualified":
		return "**Supported**"
	case "n_a":
		return "N/A"
	default:
		return "Not supported (`" + status + "`)"
	}
}

func durationLiteral(duration interface{ Nanoseconds() int64 }) string {
	nanos := duration.Nanoseconds()
	if nanos%int64(60_000_000_000) == 0 {
		return fmt.Sprintf("%d * time.Minute", nanos/int64(60_000_000_000))
	}
	if nanos%int64(1_000_000_000) == 0 {
		return fmt.Sprintf("%d * time.Second", nanos/int64(1_000_000_000))
	}
	return fmt.Sprintf("time.Duration(%d)", nanos)
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.ReplaceAll(value, "\n", " ")
}

func codeList(values []string) string {
	if len(values) == 0 {
		return "—"
	}
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = "`" + markdownCell(value) + "`"
	}
	return strings.Join(quoted, ", ")
}

func sortedMapKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
