// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/receiver/ciscoosreceiver")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/receiver/ciscoosreceiver")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                        metric.Meter
	mu                                           sync.Mutex
	registrations                                []metric.Registration
	CiscoosreceiverGnmiAuthenticationFailures    metric.Int64Counter
	CiscoosreceiverGnmiAuxiliaryStateUtilization metric.Float64Gauge
	CiscoosreceiverGnmiCacheOwnerResets          metric.Int64Counter
	CiscoosreceiverGnmiCacheUtilization          metric.Float64Gauge
	CiscoosreceiverGnmiConnections               metric.Int64Gauge
	CiscoosreceiverGnmiConsumerRefusals          metric.Int64Counter
	CiscoosreceiverGnmiDecodeErrors              metric.Int64Counter
	CiscoosreceiverGnmiDeletes                   metric.Int64Counter
	CiscoosreceiverGnmiDuplicateUpdates          metric.Int64Counter
	CiscoosreceiverGnmiInvalidTimestamps         metric.Int64Counter
	CiscoosreceiverGnmiLastSuccessUnixtime       metric.Int64Gauge
	CiscoosreceiverGnmiPreflightFailures         metric.Int64Counter
	CiscoosreceiverGnmiProductVerified           metric.Int64Gauge
	CiscoosreceiverGnmiProfileDegraded           metric.Int64Gauge
	CiscoosreceiverGnmiReconnects                metric.Int64Counter
	CiscoosreceiverGnmiSubscriptions             metric.Int64Gauge
	CiscoosreceiverGnmiUnmappedValues            metric.Int64Counter
	CiscoosreceiverGnmiUnsupportedValueKinds     metric.Int64Counter
	CiscoosreceiverGnmiUpdates                   metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.CiscoosreceiverGnmiAuthenticationFailures, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_authentication_failures",
		metric.WithDescription("Number of gNMI authentication or authorization failures [Development]"),
		metric.WithUnit("{failure}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiAuxiliaryStateUtilization, err = builder.meter.Float64Gauge(
		"otelcol_ciscoosreceiver_gnmi_auxiliary_state_utilization",
		metric.WithDescription("Maximum of the retained-entry and retained-byte utilization for the target's gNMI auxiliary-state partition [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiCacheOwnerResets, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_cache_owner_resets",
		metric.WithDescription("Number of silent owner-scoped gNMI cache resets performed before an updates-only stream reconnects [Development]"),
		metric.WithUnit("{reset}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiCacheUtilization, err = builder.meter.Float64Gauge(
		"otelcol_ciscoosreceiver_gnmi_cache_utilization",
		metric.WithDescription("Maximum of the retained-entry and retained-byte utilization for the target's gNMI cache partition [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiConnections, err = builder.meter.Int64Gauge(
		"otelcol_ciscoosreceiver_gnmi_connections",
		metric.WithDescription("Current number of established gNMI connections [Development]"),
		metric.WithUnit("{connection}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiConsumerRefusals, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_consumer_refusals",
		metric.WithDescription("Number of metric chunks refused by the downstream consumer before the affected gNMI profile reconnects [Development]"),
		metric.WithUnit("{refusal}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiDecodeErrors, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_decode_errors",
		metric.WithDescription("Number of gNMI notifications that could not be decoded [Development]"),
		metric.WithUnit("{error}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiDeletes, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_deletes",
		metric.WithDescription("Number of gNMI delete paths applied to the state cache [Development]"),
		metric.WithUnit("{delete}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiDuplicateUpdates, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_duplicate_updates",
		metric.WithDescription("Number of duplicate gNMI leaf updates suppressed by the state cache [Development]"),
		metric.WithUnit("{update}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiInvalidTimestamps, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_invalid_timestamps",
		metric.WithDescription("Number of invalid Cisco timestamps replaced with receipt time [Development]"),
		metric.WithUnit("{timestamp}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiLastSuccessUnixtime, err = builder.meter.Int64Gauge(
		"otelcol_ciscoosreceiver_gnmi_last_success_unixtime",
		metric.WithDescription("Unix time of the most recent successfully decoded gNMI notification [Development]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiPreflightFailures, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_preflight_failures",
		metric.WithDescription("Number of terminal gNMI product qualification failures. This metric emits only identity_missing, identity_ambiguous, product_mismatch, release_mismatch, missing_model, unsupported_encoding, or malformed_identity; profile-degradation reasons in the shared attribute catalog are not emitted here. [Development]"),
		metric.WithUnit("{failure}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiProductVerified, err = builder.meter.Int64Gauge(
		"otelcol_ciscoosreceiver_gnmi_product_verified",
		metric.WithDescription("Whether the gNMI target passed product, model, release, and capability verification [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiProfileDegraded, err = builder.meter.Int64Gauge(
		"otelcol_ciscoosreceiver_gnmi_profile_degraded",
		metric.WithDescription("Whether a gNMI profile is degraded (1 = degraded, 0 = healthy) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiReconnects, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_reconnects",
		metric.WithDescription("Number of gNMI transport reconnect attempts [Development]"),
		metric.WithUnit("{reconnect}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiSubscriptions, err = builder.meter.Int64Gauge(
		"otelcol_ciscoosreceiver_gnmi_subscriptions",
		metric.WithDescription("Current number of active gNMI subscription streams [Development]"),
		metric.WithUnit("{subscription}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiUnmappedValues, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_unmapped_values",
		metric.WithDescription("Number of decoded gNMI values without an explicit metric mapping [Development]"),
		metric.WithUnit("{value}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiUnsupportedValueKinds, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_unsupported_value_kinds",
		metric.WithDescription("Number of bounded opaque or aggregate gNMI TypedValues ignored by kind [Development]"),
		metric.WithUnit("{value}"),
	)
	errs = errors.Join(errs, err)
	builder.CiscoosreceiverGnmiUpdates, err = builder.meter.Int64Counter(
		"otelcol_ciscoosreceiver_gnmi_updates",
		metric.WithDescription("Number of decoded gNMI leaf updates [Development]"),
		metric.WithUnit("{update}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
