// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					CiscoDeviceUp: CiscoDeviceUpMetricConfig{
						Enabled: true,
					},
					CiscoInterfaceAdminStatus: CiscoInterfaceAdminStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceAdminStatusMetricAttributeKey{CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfaceIoRate: CiscoInterfaceIoRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceIoRateMetricAttributeKey{CiscoInterfaceIoRateMetricAttributeKeyNetworkIoDirection, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfacePacketRate: CiscoInterfacePacketRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfacePacketRateMetricAttributeKey{CiscoInterfacePacketRateMetricAttributeKeyNetworkIoDirection, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfaceSpeed: CiscoInterfaceSpeedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceSpeedMetricAttributeKey{CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfaceUtilization: CiscoInterfaceUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceUtilizationMetricAttributeKey{CiscoInterfaceUtilizationMetricAttributeKeyNetworkIoDirection, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoOpticsChromaticDispersion: CiscoOpticsChromaticDispersionMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsChromaticDispersionMetricAttributeKey{CiscoOpticsChromaticDispersionMetricAttributeKeyNetworkInterfaceName, CiscoOpticsChromaticDispersionMetricAttributeKeyCiscoOpticsLane, CiscoOpticsChromaticDispersionMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsChromaticDispersionMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsChromaticDispersionMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsDgd: CiscoOpticsDgdMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsDgdMetricAttributeKey{CiscoOpticsDgdMetricAttributeKeyNetworkInterfaceName, CiscoOpticsDgdMetricAttributeKeyCiscoOpticsLane, CiscoOpticsDgdMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsDgdMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsDgdMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsEsnr: CiscoOpticsEsnrMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsEsnrMetricAttributeKey{CiscoOpticsEsnrMetricAttributeKeyNetworkInterfaceName, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsLane, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsLaserBiasCurrent: CiscoOpticsLaserBiasCurrentMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsLaserBiasCurrentMetricAttributeKey{CiscoOpticsLaserBiasCurrentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsOsnr: CiscoOpticsOsnrMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsOsnrMetricAttributeKey{CiscoOpticsOsnrMetricAttributeKeyNetworkInterfaceName, CiscoOpticsOsnrMetricAttributeKeyCiscoOpticsLane, CiscoOpticsOsnrMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsOsnrMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsOsnrMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsPreFecBer: CiscoOpticsPreFecBerMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsPreFecBerMetricAttributeKey{CiscoOpticsPreFecBerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsPresent: CiscoOpticsPresentMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsPresentMetricAttributeKey{CiscoOpticsPresentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsQFactor: CiscoOpticsQFactorMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsQFactorMetricAttributeKey{CiscoOpticsQFactorMetricAttributeKeyNetworkInterfaceName, CiscoOpticsQFactorMetricAttributeKeyCiscoOpticsLane, CiscoOpticsQFactorMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsQFactorMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsQFactorMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsQMargin: CiscoOpticsQMarginMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsQMarginMetricAttributeKey{CiscoOpticsQMarginMetricAttributeKeyNetworkInterfaceName, CiscoOpticsQMarginMetricAttributeKeyCiscoOpticsLane, CiscoOpticsQMarginMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsQMarginMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsQMarginMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsRxPower: CiscoOpticsRxPowerMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsRxPowerMetricAttributeKey{CiscoOpticsRxPowerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTdecq: CiscoOpticsTdecqMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTdecqMetricAttributeKey{CiscoOpticsTdecqMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTecCurrent: CiscoOpticsTecCurrentMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTecCurrentMetricAttributeKey{CiscoOpticsTecCurrentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTecUtilization: CiscoOpticsTecUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTecUtilizationMetricAttributeKey{CiscoOpticsTecUtilizationMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTemperature: CiscoOpticsTemperatureMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTemperatureMetricAttributeKey{CiscoOpticsTemperatureMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTxPower: CiscoOpticsTxPowerMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTxPowerMetricAttributeKey{CiscoOpticsTxPowerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsVoltage: CiscoOpticsVoltageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsVoltageMetricAttributeKey{CiscoOpticsVoltageMetricAttributeKeyNetworkInterfaceName, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsLane, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoWlcApJoinStatus: CiscoWlcApJoinStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoWlcApJoinStatusMetricAttributeKey{CiscoWlcApJoinStatusMetricAttributeKeyCiscoWlcApMac},
					},
					CiscoWlcRfChannelUtilization: CiscoWlcRfChannelUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoWlcRfChannelUtilizationMetricAttributeKey{CiscoWlcRfChannelUtilizationMetricAttributeKeyCiscoWlcApMac, CiscoWlcRfChannelUtilizationMetricAttributeKeyCiscoWlcRadioSlot},
					},
					CiscoWlcSsidClientCount: CiscoWlcSsidClientCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoWlcSsidClientCountMetricAttributeKey{CiscoWlcSsidClientCountMetricAttributeKeyCiscoWlcApMac, CiscoWlcSsidClientCountMetricAttributeKeyCiscoWlcWlanID},
					},
					SystemCPUUtilization: SystemCPUUtilizationMetricConfig{
						Enabled: true,
					},
					SystemMemoryUtilization: SystemMemoryUtilizationMetricConfig{
						Enabled: true,
					},
					SystemNetworkErrors: SystemNetworkErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkErrorsMetricAttributeKey{SystemNetworkErrorsMetricAttributeKeyNetworkIoDirection, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceName},
					},
					SystemNetworkInterfaceStatus: SystemNetworkInterfaceStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemNetworkInterfaceStatusMetricAttributeKey{SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceName},
					},
					SystemNetworkIo: SystemNetworkIoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkIoMetricAttributeKey{SystemNetworkIoMetricAttributeKeyNetworkIoDirection, SystemNetworkIoMetricAttributeKeyNetworkInterfaceName},
					},
					SystemNetworkPacketCount: SystemNetworkPacketCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkPacketCountMetricAttributeKey{SystemNetworkPacketCountMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketCountMetricAttributeKeyNetworkPacketType, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceName},
					},
					SystemNetworkPacketDropped: SystemNetworkPacketDroppedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkPacketDroppedMetricAttributeKey{SystemNetworkPacketDroppedMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceName},
					},
					SystemUptime: SystemUptimeMetricConfig{
						Enabled: true,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					CiscoOsName:             ResourceAttributeConfig{Enabled: true},
					CiscoPlatformFamily:     ResourceAttributeConfig{Enabled: true},
					CiscoTelemetryTransport: ResourceAttributeConfig{Enabled: true},
					HostID:                  ResourceAttributeConfig{Enabled: true},
					HostIP:                  ResourceAttributeConfig{Enabled: true},
					HostName:                ResourceAttributeConfig{Enabled: true},
					HwType:                  ResourceAttributeConfig{Enabled: true},
					OsName:                  ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					CiscoDeviceUp: CiscoDeviceUpMetricConfig{
						Enabled: false,
					},
					CiscoInterfaceAdminStatus: CiscoInterfaceAdminStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceAdminStatusMetricAttributeKey{CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfaceIoRate: CiscoInterfaceIoRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceIoRateMetricAttributeKey{CiscoInterfaceIoRateMetricAttributeKeyNetworkIoDirection, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfacePacketRate: CiscoInterfacePacketRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfacePacketRateMetricAttributeKey{CiscoInterfacePacketRateMetricAttributeKeyNetworkIoDirection, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfaceSpeed: CiscoInterfaceSpeedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceSpeedMetricAttributeKey{CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoInterfaceUtilization: CiscoInterfaceUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoInterfaceUtilizationMetricAttributeKey{CiscoInterfaceUtilizationMetricAttributeKeyNetworkIoDirection, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoOpticsChromaticDispersion: CiscoOpticsChromaticDispersionMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsChromaticDispersionMetricAttributeKey{CiscoOpticsChromaticDispersionMetricAttributeKeyNetworkInterfaceName, CiscoOpticsChromaticDispersionMetricAttributeKeyCiscoOpticsLane, CiscoOpticsChromaticDispersionMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsChromaticDispersionMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsChromaticDispersionMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsDgd: CiscoOpticsDgdMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsDgdMetricAttributeKey{CiscoOpticsDgdMetricAttributeKeyNetworkInterfaceName, CiscoOpticsDgdMetricAttributeKeyCiscoOpticsLane, CiscoOpticsDgdMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsDgdMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsDgdMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsEsnr: CiscoOpticsEsnrMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsEsnrMetricAttributeKey{CiscoOpticsEsnrMetricAttributeKeyNetworkInterfaceName, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsLane, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsLaserBiasCurrent: CiscoOpticsLaserBiasCurrentMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsLaserBiasCurrentMetricAttributeKey{CiscoOpticsLaserBiasCurrentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsOsnr: CiscoOpticsOsnrMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsOsnrMetricAttributeKey{CiscoOpticsOsnrMetricAttributeKeyNetworkInterfaceName, CiscoOpticsOsnrMetricAttributeKeyCiscoOpticsLane, CiscoOpticsOsnrMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsOsnrMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsOsnrMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsPreFecBer: CiscoOpticsPreFecBerMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsPreFecBerMetricAttributeKey{CiscoOpticsPreFecBerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsPresent: CiscoOpticsPresentMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsPresentMetricAttributeKey{CiscoOpticsPresentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsQFactor: CiscoOpticsQFactorMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsQFactorMetricAttributeKey{CiscoOpticsQFactorMetricAttributeKeyNetworkInterfaceName, CiscoOpticsQFactorMetricAttributeKeyCiscoOpticsLane, CiscoOpticsQFactorMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsQFactorMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsQFactorMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsQMargin: CiscoOpticsQMarginMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsQMarginMetricAttributeKey{CiscoOpticsQMarginMetricAttributeKeyNetworkInterfaceName, CiscoOpticsQMarginMetricAttributeKeyCiscoOpticsLane, CiscoOpticsQMarginMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsQMarginMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsQMarginMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsRxPower: CiscoOpticsRxPowerMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsRxPowerMetricAttributeKey{CiscoOpticsRxPowerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTdecq: CiscoOpticsTdecqMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTdecqMetricAttributeKey{CiscoOpticsTdecqMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTecCurrent: CiscoOpticsTecCurrentMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTecCurrentMetricAttributeKey{CiscoOpticsTecCurrentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTecUtilization: CiscoOpticsTecUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTecUtilizationMetricAttributeKey{CiscoOpticsTecUtilizationMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTemperature: CiscoOpticsTemperatureMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTemperatureMetricAttributeKey{CiscoOpticsTemperatureMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsTxPower: CiscoOpticsTxPowerMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsTxPowerMetricAttributeKey{CiscoOpticsTxPowerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoOpticsVoltage: CiscoOpticsVoltageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoOpticsVoltageMetricAttributeKey{CiscoOpticsVoltageMetricAttributeKeyNetworkInterfaceName, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsLane, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsExperimental},
					},
					CiscoWlcApJoinStatus: CiscoWlcApJoinStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoWlcApJoinStatusMetricAttributeKey{CiscoWlcApJoinStatusMetricAttributeKeyCiscoWlcApMac},
					},
					CiscoWlcRfChannelUtilization: CiscoWlcRfChannelUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoWlcRfChannelUtilizationMetricAttributeKey{CiscoWlcRfChannelUtilizationMetricAttributeKeyCiscoWlcApMac, CiscoWlcRfChannelUtilizationMetricAttributeKeyCiscoWlcRadioSlot},
					},
					CiscoWlcSsidClientCount: CiscoWlcSsidClientCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoWlcSsidClientCountMetricAttributeKey{CiscoWlcSsidClientCountMetricAttributeKeyCiscoWlcApMac, CiscoWlcSsidClientCountMetricAttributeKeyCiscoWlcWlanID},
					},
					SystemCPUUtilization: SystemCPUUtilizationMetricConfig{
						Enabled: false,
					},
					SystemMemoryUtilization: SystemMemoryUtilizationMetricConfig{
						Enabled: false,
					},
					SystemNetworkErrors: SystemNetworkErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkErrorsMetricAttributeKey{SystemNetworkErrorsMetricAttributeKeyNetworkIoDirection, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceName},
					},
					SystemNetworkInterfaceStatus: SystemNetworkInterfaceStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemNetworkInterfaceStatusMetricAttributeKey{SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceName},
					},
					SystemNetworkIo: SystemNetworkIoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkIoMetricAttributeKey{SystemNetworkIoMetricAttributeKeyNetworkIoDirection, SystemNetworkIoMetricAttributeKeyNetworkInterfaceName},
					},
					SystemNetworkPacketCount: SystemNetworkPacketCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkPacketCountMetricAttributeKey{SystemNetworkPacketCountMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketCountMetricAttributeKeyNetworkPacketType, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceName},
					},
					SystemNetworkPacketDropped: SystemNetworkPacketDroppedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SystemNetworkPacketDroppedMetricAttributeKey{SystemNetworkPacketDroppedMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceName},
					},
					SystemUptime: SystemUptimeMetricConfig{
						Enabled: false,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					CiscoOsName:             ResourceAttributeConfig{Enabled: false},
					CiscoPlatformFamily:     ResourceAttributeConfig{Enabled: false},
					CiscoTelemetryTransport: ResourceAttributeConfig{Enabled: false},
					HostID:                  ResourceAttributeConfig{Enabled: false},
					HostIP:                  ResourceAttributeConfig{Enabled: false},
					HostName:                ResourceAttributeConfig{Enabled: false},
					HwType:                  ResourceAttributeConfig{Enabled: false},
					OsName:                  ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(CiscoDeviceUpMetricConfig{}, CiscoInterfaceAdminStatusMetricConfig{}, CiscoInterfaceIoRateMetricConfig{}, CiscoInterfacePacketRateMetricConfig{}, CiscoInterfaceSpeedMetricConfig{}, CiscoInterfaceUtilizationMetricConfig{}, CiscoOpticsChromaticDispersionMetricConfig{}, CiscoOpticsDgdMetricConfig{}, CiscoOpticsEsnrMetricConfig{}, CiscoOpticsLaserBiasCurrentMetricConfig{}, CiscoOpticsOsnrMetricConfig{}, CiscoOpticsPreFecBerMetricConfig{}, CiscoOpticsPresentMetricConfig{}, CiscoOpticsQFactorMetricConfig{}, CiscoOpticsQMarginMetricConfig{}, CiscoOpticsRxPowerMetricConfig{}, CiscoOpticsTdecqMetricConfig{}, CiscoOpticsTecCurrentMetricConfig{}, CiscoOpticsTecUtilizationMetricConfig{}, CiscoOpticsTemperatureMetricConfig{}, CiscoOpticsTxPowerMetricConfig{}, CiscoOpticsVoltageMetricConfig{}, CiscoWlcApJoinStatusMetricConfig{}, CiscoWlcRfChannelUtilizationMetricConfig{}, CiscoWlcSsidClientCountMetricConfig{}, SystemCPUUtilizationMetricConfig{}, SystemMemoryUtilizationMetricConfig{}, SystemNetworkErrorsMetricConfig{}, SystemNetworkInterfaceStatusMetricConfig{}, SystemNetworkIoMetricConfig{}, SystemNetworkPacketCountMetricConfig{}, SystemNetworkPacketDroppedMetricConfig{}, SystemUptimeMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func TestCiscoInterfaceAdminStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoInterfaceAdminStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoInterfaceAdminStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.interface.admin.status doesn't have an attribute invalid, valid attributes: [network.interface.name]")

	cfg = DefaultMetricsConfig().CiscoInterfaceAdminStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoInterfaceIoRateMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoInterfaceIoRate
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoInterfaceIoRateMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.interface.io.rate doesn't have an attribute invalid, valid attributes: [network.io.direction, network.interface.name]")

	cfg = DefaultMetricsConfig().CiscoInterfaceIoRate
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoInterfacePacketRateMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoInterfacePacketRate
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoInterfacePacketRateMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.interface.packet.rate doesn't have an attribute invalid, valid attributes: [network.io.direction, network.interface.name]")

	cfg = DefaultMetricsConfig().CiscoInterfacePacketRate
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoInterfaceSpeedMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoInterfaceSpeed
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoInterfaceSpeedMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.interface.speed doesn't have an attribute invalid, valid attributes: [network.interface.name]")

	cfg = DefaultMetricsConfig().CiscoInterfaceSpeed
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoInterfaceUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoInterfaceUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoInterfaceUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.interface.utilization doesn't have an attribute invalid, valid attributes: [network.io.direction, network.interface.name]")

	cfg = DefaultMetricsConfig().CiscoInterfaceUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsChromaticDispersionMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsChromaticDispersion
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsChromaticDispersionMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.chromatic_dispersion doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsChromaticDispersion
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsDgdMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsDgd
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsDgdMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.dgd doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsDgd
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsEsnrMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsEsnr
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsEsnrMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.esnr doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsEsnr
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsLaserBiasCurrentMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsLaserBiasCurrent
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsLaserBiasCurrentMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.laser_bias_current doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsLaserBiasCurrent
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsOsnrMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsOsnr
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsOsnrMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.osnr doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsOsnr
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsPreFecBerMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsPreFecBer
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsPreFecBerMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.pre_fec_ber doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsPreFecBer
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsPresentMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsPresent
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsPresentMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.present doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsPresent
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsQFactorMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsQFactor
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsQFactorMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.q_factor doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsQFactor
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsQMarginMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsQMargin
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsQMarginMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.q_margin doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsQMargin
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsRxPowerMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsRxPower
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsRxPowerMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.rx_power doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsRxPower
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsTdecqMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsTdecq
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsTdecqMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.tdecq doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsTdecq
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsTecCurrentMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsTecCurrent
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsTecCurrentMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.tec_current doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsTecCurrent
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsTecUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsTecUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsTecUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.tec_utilization doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsTecUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsTemperatureMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsTemperature
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsTemperatureMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.temperature doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsTemperature
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsTxPowerMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsTxPower
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsTxPowerMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.tx_power doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsTxPower
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoOpticsVoltageMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoOpticsVoltage
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoOpticsVoltageMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.optics.voltage doesn't have an attribute invalid, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]")

	cfg = DefaultMetricsConfig().CiscoOpticsVoltage
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoWlcApJoinStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoWlcApJoinStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoWlcApJoinStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.wlc.ap.join.status doesn't have an attribute invalid, valid attributes: [cisco.wlc.ap.mac]")

	cfg = DefaultMetricsConfig().CiscoWlcApJoinStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoWlcRfChannelUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoWlcRfChannelUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoWlcRfChannelUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.wlc.rf.channel.utilization doesn't have an attribute invalid, valid attributes: [cisco.wlc.ap.mac, cisco.wlc.radio.slot]")

	cfg = DefaultMetricsConfig().CiscoWlcRfChannelUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestCiscoWlcSsidClientCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().CiscoWlcSsidClientCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []CiscoWlcSsidClientCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric cisco.wlc.ssid.client.count doesn't have an attribute invalid, valid attributes: [cisco.wlc.ap.mac, cisco.wlc.wlan.id]")

	cfg = DefaultMetricsConfig().CiscoWlcSsidClientCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSystemNetworkErrorsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkErrors
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkErrorsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.errors doesn't have an attribute invalid, valid attributes: [network.io.direction, network.interface.name]")

	cfg = DefaultMetricsConfig().SystemNetworkErrors
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSystemNetworkInterfaceStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkInterfaceStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkInterfaceStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.interface.status doesn't have an attribute invalid, valid attributes: [network.interface.name]")

	cfg = DefaultMetricsConfig().SystemNetworkInterfaceStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSystemNetworkIoMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkIo
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkIoMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.io doesn't have an attribute invalid, valid attributes: [network.io.direction, network.interface.name]")

	cfg = DefaultMetricsConfig().SystemNetworkIo
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSystemNetworkPacketCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkPacketCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkPacketCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.packet.count doesn't have an attribute invalid, valid attributes: [network.io.direction, network.packet.type, network.interface.name]")

	cfg = DefaultMetricsConfig().SystemNetworkPacketCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSystemNetworkPacketDroppedMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SystemNetworkPacketDropped
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SystemNetworkPacketDroppedMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric system.network.packet.dropped doesn't have an attribute invalid, valid attributes: [network.io.direction, network.interface.name]")

	cfg = DefaultMetricsConfig().SystemNetworkPacketDropped
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				CiscoOsName:             ResourceAttributeConfig{Enabled: true},
				CiscoPlatformFamily:     ResourceAttributeConfig{Enabled: true},
				CiscoTelemetryTransport: ResourceAttributeConfig{Enabled: true},
				HostID:                  ResourceAttributeConfig{Enabled: true},
				HostIP:                  ResourceAttributeConfig{Enabled: true},
				HostName:                ResourceAttributeConfig{Enabled: true},
				HwType:                  ResourceAttributeConfig{Enabled: true},
				OsName:                  ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				CiscoOsName:             ResourceAttributeConfig{Enabled: false},
				CiscoPlatformFamily:     ResourceAttributeConfig{Enabled: false},
				CiscoTelemetryTransport: ResourceAttributeConfig{Enabled: false},
				HostID:                  ResourceAttributeConfig{Enabled: false},
				HostIP:                  ResourceAttributeConfig{Enabled: false},
				HostName:                ResourceAttributeConfig{Enabled: false},
				HwType:                  ResourceAttributeConfig{Enabled: false},
				OsName:                  ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
