// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetCiscoOsName sets provided value as "cisco.os.name" attribute.
func (rb *ResourceBuilder) SetCiscoOsName(val string) {
	if rb.config.CiscoOsName.Enabled {
		rb.res.Attributes().PutStr("cisco.os.name", val)
	}
}

// SetCiscoPlatformFamily sets provided value as "cisco.platform.family" attribute.
func (rb *ResourceBuilder) SetCiscoPlatformFamily(val string) {
	if rb.config.CiscoPlatformFamily.Enabled {
		rb.res.Attributes().PutStr("cisco.platform.family", val)
	}
}

// SetCiscoTelemetryTransport sets provided value as "cisco.telemetry.transport" attribute.
func (rb *ResourceBuilder) SetCiscoTelemetryTransport(val string) {
	if rb.config.CiscoTelemetryTransport.Enabled {
		rb.res.Attributes().PutStr("cisco.telemetry.transport", val)
	}
}

// SetHostID sets provided value as "host.id" attribute.
func (rb *ResourceBuilder) SetHostID(val string) {
	if rb.config.HostID.Enabled {
		rb.res.Attributes().PutStr("host.id", val)
	}
}

// SetHostIP sets provided value as "host.ip" attribute.
func (rb *ResourceBuilder) SetHostIP(val string) {
	if rb.config.HostIP.Enabled {
		rb.res.Attributes().PutStr("host.ip", val)
	}
}

// SetHostName sets provided value as "host.name" attribute.
func (rb *ResourceBuilder) SetHostName(val string) {
	if rb.config.HostName.Enabled {
		rb.res.Attributes().PutStr("host.name", val)
	}
}

// SetHwType sets provided value as "hw.type" attribute.
func (rb *ResourceBuilder) SetHwType(val string) {
	if rb.config.HwType.Enabled {
		rb.res.Attributes().PutStr("hw.type", val)
	}
}

// SetOsName sets provided value as "os.name" attribute.
func (rb *ResourceBuilder) SetOsName(val string) {
	if rb.config.OsName.Enabled {
		rb.res.Attributes().PutStr("os.name", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
