// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// CiscoDeviceUpMetricConfig provides config for the cisco.device.up metric.
type CiscoDeviceUpMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *CiscoDeviceUpMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// CiscoInterfaceAdminStatusMetricAttributeKey specifies the key of an attribute for the cisco.interface.admin.status metric.
type CiscoInterfaceAdminStatusMetricAttributeKey string

const (
	CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceName CiscoInterfaceAdminStatusMetricAttributeKey = "network.interface.name"
)

// CiscoInterfaceAdminStatusMetricConfig provides config for the cisco.interface.admin.status metric.
type CiscoInterfaceAdminStatusMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                        `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoInterfaceAdminStatusMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoInterfaceAdminStatusMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoInterfaceAdminStatusMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric cisco.interface.admin.status doesn't have an attribute %v, valid attributes: [network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoInterfaceIoRateMetricAttributeKey specifies the key of an attribute for the cisco.interface.io.rate metric.
type CiscoInterfaceIoRateMetricAttributeKey string

const (
	CiscoInterfaceIoRateMetricAttributeKeyNetworkIoDirection   CiscoInterfaceIoRateMetricAttributeKey = "network.io.direction"
	CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceName CiscoInterfaceIoRateMetricAttributeKey = "network.interface.name"
)

// CiscoInterfaceIoRateMetricConfig provides config for the cisco.interface.io.rate metric.
type CiscoInterfaceIoRateMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoInterfaceIoRateMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoInterfaceIoRateMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoInterfaceIoRateMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoInterfaceIoRateMetricAttributeKeyNetworkIoDirection, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric cisco.interface.io.rate doesn't have an attribute %v, valid attributes: [network.io.direction, network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoInterfacePacketRateMetricAttributeKey specifies the key of an attribute for the cisco.interface.packet.rate metric.
type CiscoInterfacePacketRateMetricAttributeKey string

const (
	CiscoInterfacePacketRateMetricAttributeKeyNetworkIoDirection   CiscoInterfacePacketRateMetricAttributeKey = "network.io.direction"
	CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceName CiscoInterfacePacketRateMetricAttributeKey = "network.interface.name"
)

// CiscoInterfacePacketRateMetricConfig provides config for the cisco.interface.packet.rate metric.
type CiscoInterfacePacketRateMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                       `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoInterfacePacketRateMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoInterfacePacketRateMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoInterfacePacketRateMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoInterfacePacketRateMetricAttributeKeyNetworkIoDirection, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric cisco.interface.packet.rate doesn't have an attribute %v, valid attributes: [network.io.direction, network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoInterfaceSpeedMetricAttributeKey specifies the key of an attribute for the cisco.interface.speed metric.
type CiscoInterfaceSpeedMetricAttributeKey string

const (
	CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceName CiscoInterfaceSpeedMetricAttributeKey = "network.interface.name"
)

// CiscoInterfaceSpeedMetricConfig provides config for the cisco.interface.speed metric.
type CiscoInterfaceSpeedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                  `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoInterfaceSpeedMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoInterfaceSpeedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoInterfaceSpeedMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric cisco.interface.speed doesn't have an attribute %v, valid attributes: [network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoInterfaceUtilizationMetricAttributeKey specifies the key of an attribute for the cisco.interface.utilization metric.
type CiscoInterfaceUtilizationMetricAttributeKey string

const (
	CiscoInterfaceUtilizationMetricAttributeKeyNetworkIoDirection   CiscoInterfaceUtilizationMetricAttributeKey = "network.io.direction"
	CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceName CiscoInterfaceUtilizationMetricAttributeKey = "network.interface.name"
)

// CiscoInterfaceUtilizationMetricConfig provides config for the cisco.interface.utilization metric.
type CiscoInterfaceUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                        `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoInterfaceUtilizationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoInterfaceUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoInterfaceUtilizationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoInterfaceUtilizationMetricAttributeKeyNetworkIoDirection, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric cisco.interface.utilization doesn't have an attribute %v, valid attributes: [network.io.direction, network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsEsnrMetricAttributeKey specifies the key of an attribute for the cisco.optics.esnr metric.
type CiscoOpticsEsnrMetricAttributeKey string

const (
	CiscoOpticsEsnrMetricAttributeKeyNetworkInterfaceName    CiscoOpticsEsnrMetricAttributeKey = "network.interface.name"
	CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsLane         CiscoOpticsEsnrMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsEsnrMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsEsnrMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsEsnrMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsEsnrMetricConfig provides config for the cisco.optics.esnr metric.
type CiscoOpticsEsnrMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                              `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsEsnrMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsEsnrMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsEsnrMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsEsnrMetricAttributeKeyNetworkInterfaceName, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsLane, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.esnr doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsLaserBiasCurrentMetricAttributeKey specifies the key of an attribute for the cisco.optics.laser_bias_current metric.
type CiscoOpticsLaserBiasCurrentMetricAttributeKey string

const (
	CiscoOpticsLaserBiasCurrentMetricAttributeKeyNetworkInterfaceName    CiscoOpticsLaserBiasCurrentMetricAttributeKey = "network.interface.name"
	CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsLane         CiscoOpticsLaserBiasCurrentMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsLaserBiasCurrentMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsLaserBiasCurrentMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsLaserBiasCurrentMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsLaserBiasCurrentMetricConfig provides config for the cisco.optics.laser_bias_current metric.
type CiscoOpticsLaserBiasCurrentMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsLaserBiasCurrentMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsLaserBiasCurrentMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsLaserBiasCurrentMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsLaserBiasCurrentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.laser_bias_current doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsPreFecBerMetricAttributeKey specifies the key of an attribute for the cisco.optics.pre_fec_ber metric.
type CiscoOpticsPreFecBerMetricAttributeKey string

const (
	CiscoOpticsPreFecBerMetricAttributeKeyNetworkInterfaceName    CiscoOpticsPreFecBerMetricAttributeKey = "network.interface.name"
	CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsLane         CiscoOpticsPreFecBerMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsPreFecBerMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsPreFecBerMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsPreFecBerMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsPreFecBerMetricConfig provides config for the cisco.optics.pre_fec_ber metric.
type CiscoOpticsPreFecBerMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsPreFecBerMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsPreFecBerMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsPreFecBerMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsPreFecBerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.pre_fec_ber doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsPresentMetricAttributeKey specifies the key of an attribute for the cisco.optics.present metric.
type CiscoOpticsPresentMetricAttributeKey string

const (
	CiscoOpticsPresentMetricAttributeKeyNetworkInterfaceName    CiscoOpticsPresentMetricAttributeKey = "network.interface.name"
	CiscoOpticsPresentMetricAttributeKeyCiscoOpticsLane         CiscoOpticsPresentMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsPresentMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsPresentMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsPresentMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsPresentMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsPresentMetricConfig provides config for the cisco.optics.present metric.
type CiscoOpticsPresentMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsPresentMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsPresentMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsPresentMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsPresentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.present doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsRxPowerMetricAttributeKey specifies the key of an attribute for the cisco.optics.rx_power metric.
type CiscoOpticsRxPowerMetricAttributeKey string

const (
	CiscoOpticsRxPowerMetricAttributeKeyNetworkInterfaceName    CiscoOpticsRxPowerMetricAttributeKey = "network.interface.name"
	CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsLane         CiscoOpticsRxPowerMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsRxPowerMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsRxPowerMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsRxPowerMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsRxPowerMetricConfig provides config for the cisco.optics.rx_power metric.
type CiscoOpticsRxPowerMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsRxPowerMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsRxPowerMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsRxPowerMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsRxPowerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.rx_power doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsTdecqMetricAttributeKey specifies the key of an attribute for the cisco.optics.tdecq metric.
type CiscoOpticsTdecqMetricAttributeKey string

const (
	CiscoOpticsTdecqMetricAttributeKeyNetworkInterfaceName    CiscoOpticsTdecqMetricAttributeKey = "network.interface.name"
	CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsLane         CiscoOpticsTdecqMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsTdecqMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsTdecqMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsTdecqMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsTdecqMetricConfig provides config for the cisco.optics.tdecq metric.
type CiscoOpticsTdecqMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                               `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsTdecqMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsTdecqMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsTdecqMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsTdecqMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.tdecq doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsTecCurrentMetricAttributeKey specifies the key of an attribute for the cisco.optics.tec_current metric.
type CiscoOpticsTecCurrentMetricAttributeKey string

const (
	CiscoOpticsTecCurrentMetricAttributeKeyNetworkInterfaceName    CiscoOpticsTecCurrentMetricAttributeKey = "network.interface.name"
	CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsLane         CiscoOpticsTecCurrentMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsTecCurrentMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsTecCurrentMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsTecCurrentMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsTecCurrentMetricConfig provides config for the cisco.optics.tec_current metric.
type CiscoOpticsTecCurrentMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsTecCurrentMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsTecCurrentMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsTecCurrentMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsTecCurrentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.tec_current doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsTecUtilizationMetricAttributeKey specifies the key of an attribute for the cisco.optics.tec_utilization metric.
type CiscoOpticsTecUtilizationMetricAttributeKey string

const (
	CiscoOpticsTecUtilizationMetricAttributeKeyNetworkInterfaceName    CiscoOpticsTecUtilizationMetricAttributeKey = "network.interface.name"
	CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsLane         CiscoOpticsTecUtilizationMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsTecUtilizationMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsTecUtilizationMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsTecUtilizationMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsTecUtilizationMetricConfig provides config for the cisco.optics.tec_utilization metric.
type CiscoOpticsTecUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                        `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsTecUtilizationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsTecUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsTecUtilizationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsTecUtilizationMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.tec_utilization doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsTemperatureMetricAttributeKey specifies the key of an attribute for the cisco.optics.temperature metric.
type CiscoOpticsTemperatureMetricAttributeKey string

const (
	CiscoOpticsTemperatureMetricAttributeKeyNetworkInterfaceName    CiscoOpticsTemperatureMetricAttributeKey = "network.interface.name"
	CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsLane         CiscoOpticsTemperatureMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsTemperatureMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsTemperatureMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsTemperatureMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsTemperatureMetricConfig provides config for the cisco.optics.temperature metric.
type CiscoOpticsTemperatureMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsTemperatureMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsTemperatureMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsTemperatureMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsTemperatureMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.temperature doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsTxPowerMetricAttributeKey specifies the key of an attribute for the cisco.optics.tx_power metric.
type CiscoOpticsTxPowerMetricAttributeKey string

const (
	CiscoOpticsTxPowerMetricAttributeKeyNetworkInterfaceName    CiscoOpticsTxPowerMetricAttributeKey = "network.interface.name"
	CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsLane         CiscoOpticsTxPowerMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsTxPowerMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsTxPowerMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsTxPowerMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsTxPowerMetricConfig provides config for the cisco.optics.tx_power metric.
type CiscoOpticsTxPowerMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsTxPowerMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsTxPowerMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsTxPowerMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsTxPowerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.tx_power doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// CiscoOpticsVoltageMetricAttributeKey specifies the key of an attribute for the cisco.optics.voltage metric.
type CiscoOpticsVoltageMetricAttributeKey string

const (
	CiscoOpticsVoltageMetricAttributeKeyNetworkInterfaceName    CiscoOpticsVoltageMetricAttributeKey = "network.interface.name"
	CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsLane         CiscoOpticsVoltageMetricAttributeKey = "cisco.optics.lane"
	CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsSensor       CiscoOpticsVoltageMetricAttributeKey = "cisco.optics.sensor"
	CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsProfile      CiscoOpticsVoltageMetricAttributeKey = "cisco.optics.profile"
	CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsExperimental CiscoOpticsVoltageMetricAttributeKey = "cisco.optics.experimental"
)

// CiscoOpticsVoltageMetricConfig provides config for the cisco.optics.voltage metric.
type CiscoOpticsVoltageMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []CiscoOpticsVoltageMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *CiscoOpticsVoltageMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *CiscoOpticsVoltageMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case CiscoOpticsVoltageMetricAttributeKeyNetworkInterfaceName, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsLane, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsExperimental:
		default:
			return fmt.Errorf("metric cisco.optics.voltage doesn't have an attribute %v, valid attributes: [network.interface.name, cisco.optics.lane, cisco.optics.sensor, cisco.optics.profile, cisco.optics.experimental]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemCPUUtilizationMetricAttributeKey specifies the key of an attribute for the system.cpu.utilization metric.
type SystemCPUUtilizationMetricAttributeKey string

const (
	SystemCPUUtilizationMetricAttributeKeyCiscoNodeName SystemCPUUtilizationMetricAttributeKey = "cisco.node.name"
)

// SystemCPUUtilizationMetricConfig provides config for the system.cpu.utilization metric.
type SystemCPUUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemCPUUtilizationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemCPUUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemCPUUtilizationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemCPUUtilizationMetricAttributeKeyCiscoNodeName:
		default:
			return fmt.Errorf("metric system.cpu.utilization doesn't have an attribute %v, valid attributes: [cisco.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemMemoryUtilizationMetricAttributeKey specifies the key of an attribute for the system.memory.utilization metric.
type SystemMemoryUtilizationMetricAttributeKey string

const (
	SystemMemoryUtilizationMetricAttributeKeyCiscoLocationFru     SystemMemoryUtilizationMetricAttributeKey = "cisco.location.fru"
	SystemMemoryUtilizationMetricAttributeKeyCiscoLocationSlot    SystemMemoryUtilizationMetricAttributeKey = "cisco.location.slot"
	SystemMemoryUtilizationMetricAttributeKeyCiscoLocationBay     SystemMemoryUtilizationMetricAttributeKey = "cisco.location.bay"
	SystemMemoryUtilizationMetricAttributeKeyCiscoLocationChassis SystemMemoryUtilizationMetricAttributeKey = "cisco.location.chassis"
)

// SystemMemoryUtilizationMetricConfig provides config for the system.memory.utilization metric.
type SystemMemoryUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemMemoryUtilizationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemMemoryUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemMemoryUtilizationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemMemoryUtilizationMetricAttributeKeyCiscoLocationFru, SystemMemoryUtilizationMetricAttributeKeyCiscoLocationSlot, SystemMemoryUtilizationMetricAttributeKeyCiscoLocationBay, SystemMemoryUtilizationMetricAttributeKeyCiscoLocationChassis:
		default:
			return fmt.Errorf("metric system.memory.utilization doesn't have an attribute %v, valid attributes: [cisco.location.fru, cisco.location.slot, cisco.location.bay, cisco.location.chassis]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemNetworkErrorsMetricAttributeKey specifies the key of an attribute for the system.network.errors metric.
type SystemNetworkErrorsMetricAttributeKey string

const (
	SystemNetworkErrorsMetricAttributeKeyNetworkIoDirection   SystemNetworkErrorsMetricAttributeKey = "network.io.direction"
	SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceName SystemNetworkErrorsMetricAttributeKey = "network.interface.name"
)

// SystemNetworkErrorsMetricConfig provides config for the system.network.errors metric.
type SystemNetworkErrorsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                  `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkErrorsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkErrorsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemNetworkErrorsMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemNetworkErrorsMetricAttributeKeyNetworkIoDirection, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric system.network.errors doesn't have an attribute %v, valid attributes: [network.io.direction, network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemNetworkInterfaceStatusMetricAttributeKey specifies the key of an attribute for the system.network.interface.status metric.
type SystemNetworkInterfaceStatusMetricAttributeKey string

const (
	SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceName SystemNetworkInterfaceStatusMetricAttributeKey = "network.interface.name"
)

// SystemNetworkInterfaceStatusMetricConfig provides config for the system.network.interface.status metric.
type SystemNetworkInterfaceStatusMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                           `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkInterfaceStatusMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkInterfaceStatusMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemNetworkInterfaceStatusMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric system.network.interface.status doesn't have an attribute %v, valid attributes: [network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemNetworkIoMetricAttributeKey specifies the key of an attribute for the system.network.io metric.
type SystemNetworkIoMetricAttributeKey string

const (
	SystemNetworkIoMetricAttributeKeyNetworkIoDirection   SystemNetworkIoMetricAttributeKey = "network.io.direction"
	SystemNetworkIoMetricAttributeKeyNetworkInterfaceName SystemNetworkIoMetricAttributeKey = "network.interface.name"
)

// SystemNetworkIoMetricConfig provides config for the system.network.io metric.
type SystemNetworkIoMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                              `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkIoMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkIoMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemNetworkIoMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemNetworkIoMetricAttributeKeyNetworkIoDirection, SystemNetworkIoMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric system.network.io doesn't have an attribute %v, valid attributes: [network.io.direction, network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemNetworkPacketCountMetricAttributeKey specifies the key of an attribute for the system.network.packet.count metric.
type SystemNetworkPacketCountMetricAttributeKey string

const (
	SystemNetworkPacketCountMetricAttributeKeyNetworkIoDirection   SystemNetworkPacketCountMetricAttributeKey = "network.io.direction"
	SystemNetworkPacketCountMetricAttributeKeyNetworkPacketType    SystemNetworkPacketCountMetricAttributeKey = "network.packet.type"
	SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceName SystemNetworkPacketCountMetricAttributeKey = "network.interface.name"
)

// SystemNetworkPacketCountMetricConfig provides config for the system.network.packet.count metric.
type SystemNetworkPacketCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                       `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkPacketCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkPacketCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemNetworkPacketCountMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemNetworkPacketCountMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketCountMetricAttributeKeyNetworkPacketType, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric system.network.packet.count doesn't have an attribute %v, valid attributes: [network.io.direction, network.packet.type, network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemNetworkPacketDroppedMetricAttributeKey specifies the key of an attribute for the system.network.packet.dropped metric.
type SystemNetworkPacketDroppedMetricAttributeKey string

const (
	SystemNetworkPacketDroppedMetricAttributeKeyNetworkIoDirection   SystemNetworkPacketDroppedMetricAttributeKey = "network.io.direction"
	SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceName SystemNetworkPacketDroppedMetricAttributeKey = "network.interface.name"
)

// SystemNetworkPacketDroppedMetricConfig provides config for the system.network.packet.dropped metric.
type SystemNetworkPacketDroppedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                         `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkPacketDroppedMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkPacketDroppedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SystemNetworkPacketDroppedMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SystemNetworkPacketDroppedMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceName:
		default:
			return fmt.Errorf("metric system.network.packet.dropped doesn't have an attribute %v, valid attributes: [network.io.direction, network.interface.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SystemUptimeMetricConfig provides config for the system.uptime metric.
type SystemUptimeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SystemUptimeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for cisco_os metrics.
type MetricsConfig struct {
	CiscoDeviceUp                CiscoDeviceUpMetricConfig                `mapstructure:"cisco.device.up"`
	CiscoInterfaceAdminStatus    CiscoInterfaceAdminStatusMetricConfig    `mapstructure:"cisco.interface.admin.status"`
	CiscoInterfaceIoRate         CiscoInterfaceIoRateMetricConfig         `mapstructure:"cisco.interface.io.rate"`
	CiscoInterfacePacketRate     CiscoInterfacePacketRateMetricConfig     `mapstructure:"cisco.interface.packet.rate"`
	CiscoInterfaceSpeed          CiscoInterfaceSpeedMetricConfig          `mapstructure:"cisco.interface.speed"`
	CiscoInterfaceUtilization    CiscoInterfaceUtilizationMetricConfig    `mapstructure:"cisco.interface.utilization"`
	CiscoOpticsEsnr              CiscoOpticsEsnrMetricConfig              `mapstructure:"cisco.optics.esnr"`
	CiscoOpticsLaserBiasCurrent  CiscoOpticsLaserBiasCurrentMetricConfig  `mapstructure:"cisco.optics.laser_bias_current"`
	CiscoOpticsPreFecBer         CiscoOpticsPreFecBerMetricConfig         `mapstructure:"cisco.optics.pre_fec_ber"`
	CiscoOpticsPresent           CiscoOpticsPresentMetricConfig           `mapstructure:"cisco.optics.present"`
	CiscoOpticsRxPower           CiscoOpticsRxPowerMetricConfig           `mapstructure:"cisco.optics.rx_power"`
	CiscoOpticsTdecq             CiscoOpticsTdecqMetricConfig             `mapstructure:"cisco.optics.tdecq"`
	CiscoOpticsTecCurrent        CiscoOpticsTecCurrentMetricConfig        `mapstructure:"cisco.optics.tec_current"`
	CiscoOpticsTecUtilization    CiscoOpticsTecUtilizationMetricConfig    `mapstructure:"cisco.optics.tec_utilization"`
	CiscoOpticsTemperature       CiscoOpticsTemperatureMetricConfig       `mapstructure:"cisco.optics.temperature"`
	CiscoOpticsTxPower           CiscoOpticsTxPowerMetricConfig           `mapstructure:"cisco.optics.tx_power"`
	CiscoOpticsVoltage           CiscoOpticsVoltageMetricConfig           `mapstructure:"cisco.optics.voltage"`
	SystemCPUUtilization         SystemCPUUtilizationMetricConfig         `mapstructure:"system.cpu.utilization"`
	SystemMemoryUtilization      SystemMemoryUtilizationMetricConfig      `mapstructure:"system.memory.utilization"`
	SystemNetworkErrors          SystemNetworkErrorsMetricConfig          `mapstructure:"system.network.errors"`
	SystemNetworkInterfaceStatus SystemNetworkInterfaceStatusMetricConfig `mapstructure:"system.network.interface.status"`
	SystemNetworkIo              SystemNetworkIoMetricConfig              `mapstructure:"system.network.io"`
	SystemNetworkPacketCount     SystemNetworkPacketCountMetricConfig     `mapstructure:"system.network.packet.count"`
	SystemNetworkPacketDropped   SystemNetworkPacketDroppedMetricConfig   `mapstructure:"system.network.packet.dropped"`
	SystemUptime                 SystemUptimeMetricConfig                 `mapstructure:"system.uptime"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		CiscoDeviceUp: CiscoDeviceUpMetricConfig{
			Enabled: true,
		},
		CiscoInterfaceAdminStatus: CiscoInterfaceAdminStatusMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoInterfaceAdminStatusMetricAttributeKey{CiscoInterfaceAdminStatusMetricAttributeKeyNetworkInterfaceName},
		},
		CiscoInterfaceIoRate: CiscoInterfaceIoRateMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoInterfaceIoRateMetricAttributeKey{CiscoInterfaceIoRateMetricAttributeKeyNetworkIoDirection, CiscoInterfaceIoRateMetricAttributeKeyNetworkInterfaceName},
		},
		CiscoInterfacePacketRate: CiscoInterfacePacketRateMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoInterfacePacketRateMetricAttributeKey{CiscoInterfacePacketRateMetricAttributeKeyNetworkIoDirection, CiscoInterfacePacketRateMetricAttributeKeyNetworkInterfaceName},
		},
		CiscoInterfaceSpeed: CiscoInterfaceSpeedMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoInterfaceSpeedMetricAttributeKey{CiscoInterfaceSpeedMetricAttributeKeyNetworkInterfaceName},
		},
		CiscoInterfaceUtilization: CiscoInterfaceUtilizationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoInterfaceUtilizationMetricAttributeKey{CiscoInterfaceUtilizationMetricAttributeKeyNetworkIoDirection, CiscoInterfaceUtilizationMetricAttributeKeyNetworkInterfaceName},
		},
		CiscoOpticsEsnr: CiscoOpticsEsnrMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsEsnrMetricAttributeKey{CiscoOpticsEsnrMetricAttributeKeyNetworkInterfaceName, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsLane, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsEsnrMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsLaserBiasCurrent: CiscoOpticsLaserBiasCurrentMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsLaserBiasCurrentMetricAttributeKey{CiscoOpticsLaserBiasCurrentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsLaserBiasCurrentMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsPreFecBer: CiscoOpticsPreFecBerMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsPreFecBerMetricAttributeKey{CiscoOpticsPreFecBerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsPreFecBerMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsPresent: CiscoOpticsPresentMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsPresentMetricAttributeKey{CiscoOpticsPresentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsPresentMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsRxPower: CiscoOpticsRxPowerMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsRxPowerMetricAttributeKey{CiscoOpticsRxPowerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsRxPowerMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsTdecq: CiscoOpticsTdecqMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsTdecqMetricAttributeKey{CiscoOpticsTdecqMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTdecqMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsTecCurrent: CiscoOpticsTecCurrentMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsTecCurrentMetricAttributeKey{CiscoOpticsTecCurrentMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTecCurrentMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsTecUtilization: CiscoOpticsTecUtilizationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsTecUtilizationMetricAttributeKey{CiscoOpticsTecUtilizationMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTecUtilizationMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsTemperature: CiscoOpticsTemperatureMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsTemperatureMetricAttributeKey{CiscoOpticsTemperatureMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTemperatureMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsTxPower: CiscoOpticsTxPowerMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsTxPowerMetricAttributeKey{CiscoOpticsTxPowerMetricAttributeKeyNetworkInterfaceName, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsLane, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsTxPowerMetricAttributeKeyCiscoOpticsExperimental},
		},
		CiscoOpticsVoltage: CiscoOpticsVoltageMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []CiscoOpticsVoltageMetricAttributeKey{CiscoOpticsVoltageMetricAttributeKeyNetworkInterfaceName, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsLane, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsSensor, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsProfile, CiscoOpticsVoltageMetricAttributeKeyCiscoOpticsExperimental},
		},
		SystemCPUUtilization: SystemCPUUtilizationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SystemCPUUtilizationMetricAttributeKey{SystemCPUUtilizationMetricAttributeKeyCiscoNodeName},
		},
		SystemMemoryUtilization: SystemMemoryUtilizationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SystemMemoryUtilizationMetricAttributeKey{SystemMemoryUtilizationMetricAttributeKeyCiscoLocationFru, SystemMemoryUtilizationMetricAttributeKeyCiscoLocationSlot, SystemMemoryUtilizationMetricAttributeKeyCiscoLocationBay, SystemMemoryUtilizationMetricAttributeKeyCiscoLocationChassis},
		},
		SystemNetworkErrors: SystemNetworkErrorsMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SystemNetworkErrorsMetricAttributeKey{SystemNetworkErrorsMetricAttributeKeyNetworkIoDirection, SystemNetworkErrorsMetricAttributeKeyNetworkInterfaceName},
		},
		SystemNetworkInterfaceStatus: SystemNetworkInterfaceStatusMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SystemNetworkInterfaceStatusMetricAttributeKey{SystemNetworkInterfaceStatusMetricAttributeKeyNetworkInterfaceName},
		},
		SystemNetworkIo: SystemNetworkIoMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SystemNetworkIoMetricAttributeKey{SystemNetworkIoMetricAttributeKeyNetworkIoDirection, SystemNetworkIoMetricAttributeKeyNetworkInterfaceName},
		},
		SystemNetworkPacketCount: SystemNetworkPacketCountMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SystemNetworkPacketCountMetricAttributeKey{SystemNetworkPacketCountMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketCountMetricAttributeKeyNetworkPacketType, SystemNetworkPacketCountMetricAttributeKeyNetworkInterfaceName},
		},
		SystemNetworkPacketDropped: SystemNetworkPacketDroppedMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SystemNetworkPacketDroppedMetricAttributeKey{SystemNetworkPacketDroppedMetricAttributeKeyNetworkIoDirection, SystemNetworkPacketDroppedMetricAttributeKeyNetworkInterfaceName},
		},
		SystemUptime: SystemUptimeMetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for cisco_os resource attributes.
type ResourceAttributesConfig struct {
	CiscoOsName             ResourceAttributeConfig `mapstructure:"cisco.os.name"`
	CiscoPlatformFamily     ResourceAttributeConfig `mapstructure:"cisco.platform.family"`
	CiscoProductFamily      ResourceAttributeConfig `mapstructure:"cisco.product.family"`
	CiscoTelemetryTransport ResourceAttributeConfig `mapstructure:"cisco.telemetry.transport"`
	DeviceManufacturer      ResourceAttributeConfig `mapstructure:"device.manufacturer"`
	DeviceModelIdentifier   ResourceAttributeConfig `mapstructure:"device.model.identifier"`
	HostID                  ResourceAttributeConfig `mapstructure:"host.id"`
	HostIP                  ResourceAttributeConfig `mapstructure:"host.ip"`
	HostName                ResourceAttributeConfig `mapstructure:"host.name"`
	HwType                  ResourceAttributeConfig `mapstructure:"hw.type"`
	OsName                  ResourceAttributeConfig `mapstructure:"os.name"`
	OsVersion               ResourceAttributeConfig `mapstructure:"os.version"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		CiscoOsName: ResourceAttributeConfig{
			Enabled: true,
		},
		CiscoPlatformFamily: ResourceAttributeConfig{
			Enabled: true,
		},
		CiscoProductFamily: ResourceAttributeConfig{
			Enabled: true,
		},
		CiscoTelemetryTransport: ResourceAttributeConfig{
			Enabled: true,
		},
		DeviceManufacturer: ResourceAttributeConfig{
			Enabled: true,
		},
		DeviceModelIdentifier: ResourceAttributeConfig{
			Enabled: true,
		},
		HostID: ResourceAttributeConfig{
			Enabled: true,
		},
		HostIP: ResourceAttributeConfig{
			Enabled: true,
		},
		HostName: ResourceAttributeConfig{
			Enabled: true,
		},
		HwType: ResourceAttributeConfig{
			Enabled: true,
		},
		OsName: ResourceAttributeConfig{
			Enabled: true,
		},
		OsVersion: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for cisco_os metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
