// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetCiscoOsName("cisco.os.name-val")
			rb.SetCiscoPlatformFamily("cisco.platform.family-val")
			rb.SetCiscoTelemetryTransport("cisco.telemetry.transport-val")
			rb.SetHostID("host.id-val")
			rb.SetHostIP("host.ip-val")
			rb.SetHostName("host.name-val")
			rb.SetHwType("hw.type-val")
			rb.SetOsName("os.name-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 8, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 8, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}
			ciscoOsNameAttrVal, ok := res.Attributes().Get("cisco.os.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "cisco.os.name-val", ciscoOsNameAttrVal.Str())
			}
			ciscoPlatformFamilyAttrVal, ok := res.Attributes().Get("cisco.platform.family")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "cisco.platform.family-val", ciscoPlatformFamilyAttrVal.Str())
			}
			ciscoTelemetryTransportAttrVal, ok := res.Attributes().Get("cisco.telemetry.transport")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "cisco.telemetry.transport-val", ciscoTelemetryTransportAttrVal.Str())
			}
			hostIDAttrVal, ok := res.Attributes().Get("host.id")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "host.id-val", hostIDAttrVal.Str())
			}
			hostIPAttrVal, ok := res.Attributes().Get("host.ip")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "host.ip-val", hostIPAttrVal.Str())
			}
			hostNameAttrVal, ok := res.Attributes().Get("host.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "host.name-val", hostNameAttrVal.Str())
			}
			hwTypeAttrVal, ok := res.Attributes().Get("hw.type")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "hw.type-val", hwTypeAttrVal.Str())
			}
			osNameAttrVal, ok := res.Attributes().Get("os.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "os.name-val", osNameAttrVal.Str())
			}
		})
	}
}
