// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					CiscoAdjacencyEntries: CiscoAdjacencyEntriesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoAdjacencyEntriesMetricAttributeKey{CiscoAdjacencyEntriesMetricAttributeKeyCiscoRoutingVrf, CiscoAdjacencyEntriesMetricAttributeKeyCiscoAdjacencyState},
					},
					CiscoArpEntries: CiscoArpEntriesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoArpEntriesMetricAttributeKey{CiscoArpEntriesMetricAttributeKeyCiscoRoutingVrf, CiscoArpEntriesMetricAttributeKeyAddressFamily},
					},
					CiscoControlPlaneCPUProcessUtilization: CiscoControlPlaneCPUProcessUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoControlPlaneCPUProcessUtilizationMetricAttributeKey{CiscoControlPlaneCPUProcessUtilizationMetricAttributeKeyCiscoProcessName, CiscoControlPlaneCPUProcessUtilizationMetricAttributeKeyCiscoProcessPid, CiscoControlPlaneCPUProcessUtilizationMetricAttributeKeyCiscoCPUWindow},
					},
					CiscoControlPlaneDropped: CiscoControlPlaneDroppedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoControlPlaneDroppedMetricAttributeKey{CiscoControlPlaneDroppedMetricAttributeKeyCiscoControlPlaneSource, CiscoControlPlaneDroppedMetricAttributeKeyCiscoControlPlaneClass, CiscoControlPlaneDroppedMetricAttributeKeyCiscoControlPlaneDropReason},
					},
					CiscoControlPlanePackets: CiscoControlPlanePacketsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoControlPlanePacketsMetricAttributeKey{CiscoControlPlanePacketsMetricAttributeKeyCiscoControlPlaneSource, CiscoControlPlanePacketsMetricAttributeKeyCiscoControlPlaneClass, CiscoControlPlanePacketsMetricAttributeKeyNetworkIoDirection},
					},
					CiscoControlPlanePuntRate: CiscoControlPlanePuntRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoControlPlanePuntRateMetricAttributeKey{CiscoControlPlanePuntRateMetricAttributeKeyCiscoControlPlanePuntQueue, CiscoControlPlanePuntRateMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoDeviceUp: CiscoDeviceUpMetricConfig{
						Enabled: true,
					},
					CiscoEvpnRoutes: CiscoEvpnRoutesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoEvpnRoutesMetricAttributeKey{CiscoEvpnRoutesMetricAttributeKeyCiscoRoutingVrf, CiscoEvpnRoutesMetricAttributeKeyCiscoEvpnRouteType},
					},
					CiscoForwardingDrops: CiscoForwardingDropsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoForwardingDropsMetricAttributeKey{CiscoForwardingDropsMetricAttributeKeyCiscoRoutingVrf, CiscoForwardingDropsMetricAttributeKeyCiscoForwardingDropReason},
					},
					CiscoForwardingFibEntries: CiscoForwardingFibEntriesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoForwardingFibEntriesMetricAttributeKey{CiscoForwardingFibEntriesMetricAttributeKeyCiscoRoutingVrf, CiscoForwardingFibEntriesMetricAttributeKeyAddressFamily},
					},
					CiscoHardwareStatus: CiscoHardwareStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoHardwareStatusMetricAttributeKey{CiscoHardwareStatusMetricAttributeKeyCiscoHardwareComponent, CiscoHardwareStatusMetricAttributeKeyCiscoHardwareName, CiscoHardwareStatusMetricAttributeKeyCiscoHardwareSlot, CiscoHardwareStatusMetricAttributeKeyCiscoHardwareState},
					},
					CiscoHardwareTemperature: CiscoHardwareTemperatureMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoHardwareTemperatureMetricAttributeKey{CiscoHardwareTemperatureMetricAttributeKeyCiscoHardwareName, CiscoHardwareTemperatureMetricAttributeKeyCiscoHardwareSlot, CiscoHardwareTemperatureMetricAttributeKeyCiscoHardwareState},
					},
					CiscoNvePeerStatus: CiscoNvePeerStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoNvePeerStatusMetricAttributeKey{CiscoNvePeerStatusMetricAttributeKeyNetworkPeerAddress, CiscoNvePeerStatusMetricAttributeKeyCiscoNveState},
					},
					CiscoNveVniStatus: CiscoNveVniStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoNveVniStatusMetricAttributeKey{CiscoNveVniStatusMetricAttributeKeyCiscoNveVni, CiscoNveVniStatusMetricAttributeKeyCiscoNveVniType, CiscoNveVniStatusMetricAttributeKeyCiscoNveState},
					},
					CiscoProtocolDropped: CiscoProtocolDroppedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoProtocolDroppedMetricAttributeKey{CiscoProtocolDroppedMetricAttributeKeyCiscoProtocolDropReason, CiscoProtocolDroppedMetricAttributeKeyCiscoProtocolName},
					},
					CiscoProtocolErrors: CiscoProtocolErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoProtocolErrorsMetricAttributeKey{CiscoProtocolErrorsMetricAttributeKeyCiscoProtocolErrorType, CiscoProtocolErrorsMetricAttributeKeyCiscoProtocolName},
					},
					CiscoProtocolPackets: CiscoProtocolPacketsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoProtocolPacketsMetricAttributeKey{CiscoProtocolPacketsMetricAttributeKeyCiscoProtocolMessageType, CiscoProtocolPacketsMetricAttributeKeyCiscoProtocolName, CiscoProtocolPacketsMetricAttributeKeyNetworkIoDirection},
					},
					CiscoQfpDatapathIo: CiscoQfpDatapathIoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoQfpDatapathIoMetricAttributeKey{CiscoQfpDatapathIoMetricAttributeKeyNetworkIoDirection, CiscoQfpDatapathIoMetricAttributeKeyCiscoQfpTrafficClass, CiscoQfpDatapathIoMetricAttributeKeyCiscoCPUWindow},
					},
					CiscoQfpDatapathPacketRate: CiscoQfpDatapathPacketRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoQfpDatapathPacketRateMetricAttributeKey{CiscoQfpDatapathPacketRateMetricAttributeKeyNetworkIoDirection, CiscoQfpDatapathPacketRateMetricAttributeKeyCiscoQfpTrafficClass, CiscoQfpDatapathPacketRateMetricAttributeKeyCiscoCPUWindow},
					},
					CiscoQfpDatapathUtilization: CiscoQfpDatapathUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoQfpDatapathUtilizationMetricAttributeKey{CiscoQfpDatapathUtilizationMetricAttributeKeyCiscoQfpLoadType, CiscoQfpDatapathUtilizationMetricAttributeKeyCiscoCPUWindow},
					},
					CiscoQfpDropBytes: CiscoQfpDropBytesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoQfpDropBytesMetricAttributeKey{CiscoQfpDropBytesMetricAttributeKeyCiscoQfpDropSource, CiscoQfpDropBytesMetricAttributeKeyCiscoForwardingDropReason},
					},
					CiscoQfpDrops: CiscoQfpDropsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoQfpDropsMetricAttributeKey{CiscoQfpDropsMetricAttributeKeyCiscoQfpDropSource, CiscoQfpDropsMetricAttributeKeyCiscoForwardingDropReason},
					},
					CiscoQfpInterfaceDrops: CiscoQfpInterfaceDropsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoQfpInterfaceDropsMetricAttributeKey{CiscoQfpInterfaceDropsMetricAttributeKeyNetworkInterfaceName, CiscoQfpInterfaceDropsMetricAttributeKeyNetworkIoDirection},
					},
					CiscoRoutingNeighborPrefixes: CiscoRoutingNeighborPrefixesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoRoutingNeighborPrefixesMetricAttributeKey{CiscoRoutingNeighborPrefixesMetricAttributeKeyCiscoRoutingProtocol, CiscoRoutingNeighborPrefixesMetricAttributeKeyCiscoRoutingVrf, CiscoRoutingNeighborPrefixesMetricAttributeKeyNetworkPeerAddress, CiscoRoutingNeighborPrefixesMetricAttributeKeyAddressFamily},
					},
					CiscoRoutingNeighborState: CiscoRoutingNeighborStateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoRoutingNeighborStateMetricAttributeKey{CiscoRoutingNeighborStateMetricAttributeKeyCiscoRoutingProtocol, CiscoRoutingNeighborStateMetricAttributeKeyCiscoRoutingVrf, CiscoRoutingNeighborStateMetricAttributeKeyNetworkPeerAddress, CiscoRoutingNeighborStateMetricAttributeKeyCiscoRoutingNeighborState, CiscoRoutingNeighborStateMetricAttributeKeyAddressFamily},
					},
					CiscoRoutingRoutes: CiscoRoutingRoutesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoRoutingRoutesMetricAttributeKey{CiscoRoutingRoutesMetricAttributeKeyCiscoRoutingVrf, CiscoRoutingRoutesMetricAttributeKeyCiscoRouteSource, CiscoRoutingRoutesMetricAttributeKeyAddressFamily},
					},
					CiscoScrapeCommandDuration: CiscoScrapeCommandDurationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoScrapeCommandDurationMetricAttributeKey{CiscoScrapeCommandDurationMetricAttributeKeyCiscoScrapeCommandFamily, CiscoScrapeCommandDurationMetricAttributeKeyCiscoScrapeCommandOutcome},
					},
					CiscoScrapeCommandErrors: CiscoScrapeCommandErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoScrapeCommandErrorsMetricAttributeKey{CiscoScrapeCommandErrorsMetricAttributeKeyCiscoScrapeCommandFamily, CiscoScrapeCommandErrorsMetricAttributeKeyCiscoScrapeErrorType},
					},
					CiscoScrapePartialSuccess: CiscoScrapePartialSuccessMetricConfig{
						Enabled: true,
					},
					CiscoSSHReconnects: CiscoSSHReconnectsMetricConfig{
						Enabled: true,
					},
					SystemCPUUtilization: SystemCPUUtilizationMetricConfig{
						Enabled: true,
					},
					SystemMemoryUtilization: SystemMemoryUtilizationMetricConfig{
						Enabled: true,
					},
					SystemUptime: SystemUptimeMetricConfig{
						Enabled: true,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostID:    ResourceAttributeConfig{Enabled: true},
					HostIP:    ResourceAttributeConfig{Enabled: true},
					HostName:  ResourceAttributeConfig{Enabled: true},
					HostType:  ResourceAttributeConfig{Enabled: true},
					HwType:    ResourceAttributeConfig{Enabled: true},
					OsName:    ResourceAttributeConfig{Enabled: true},
					OsVersion: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					CiscoAdjacencyEntries: CiscoAdjacencyEntriesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoAdjacencyEntriesMetricAttributeKey{CiscoAdjacencyEntriesMetricAttributeKeyCiscoRoutingVrf, CiscoAdjacencyEntriesMetricAttributeKeyCiscoAdjacencyState},
					},
					CiscoArpEntries: CiscoArpEntriesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoArpEntriesMetricAttributeKey{CiscoArpEntriesMetricAttributeKeyCiscoRoutingVrf, CiscoArpEntriesMetricAttributeKeyAddressFamily},
					},
					CiscoControlPlaneCPUProcessUtilization: CiscoControlPlaneCPUProcessUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoControlPlaneCPUProcessUtilizationMetricAttributeKey{CiscoControlPlaneCPUProcessUtilizationMetricAttributeKeyCiscoProcessName, CiscoControlPlaneCPUProcessUtilizationMetricAttributeKeyCiscoProcessPid, CiscoControlPlaneCPUProcessUtilizationMetricAttributeKeyCiscoCPUWindow},
					},
					CiscoControlPlaneDropped: CiscoControlPlaneDroppedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoControlPlaneDroppedMetricAttributeKey{CiscoControlPlaneDroppedMetricAttributeKeyCiscoControlPlaneSource, CiscoControlPlaneDroppedMetricAttributeKeyCiscoControlPlaneClass, CiscoControlPlaneDroppedMetricAttributeKeyCiscoControlPlaneDropReason},
					},
					CiscoControlPlanePackets: CiscoControlPlanePacketsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoControlPlanePacketsMetricAttributeKey{CiscoControlPlanePacketsMetricAttributeKeyCiscoControlPlaneSource, CiscoControlPlanePacketsMetricAttributeKeyCiscoControlPlaneClass, CiscoControlPlanePacketsMetricAttributeKeyNetworkIoDirection},
					},
					CiscoControlPlanePuntRate: CiscoControlPlanePuntRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoControlPlanePuntRateMetricAttributeKey{CiscoControlPlanePuntRateMetricAttributeKeyCiscoControlPlanePuntQueue, CiscoControlPlanePuntRateMetricAttributeKeyNetworkInterfaceName},
					},
					CiscoDeviceUp: CiscoDeviceUpMetricConfig{
						Enabled: false,
					},
					CiscoEvpnRoutes: CiscoEvpnRoutesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoEvpnRoutesMetricAttributeKey{CiscoEvpnRoutesMetricAttributeKeyCiscoRoutingVrf, CiscoEvpnRoutesMetricAttributeKeyCiscoEvpnRouteType},
					},
					CiscoForwardingDrops: CiscoForwardingDropsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoForwardingDropsMetricAttributeKey{CiscoForwardingDropsMetricAttributeKeyCiscoRoutingVrf, CiscoForwardingDropsMetricAttributeKeyCiscoForwardingDropReason},
					},
					CiscoForwardingFibEntries: CiscoForwardingFibEntriesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoForwardingFibEntriesMetricAttributeKey{CiscoForwardingFibEntriesMetricAttributeKeyCiscoRoutingVrf, CiscoForwardingFibEntriesMetricAttributeKeyAddressFamily},
					},
					CiscoHardwareStatus: CiscoHardwareStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoHardwareStatusMetricAttributeKey{CiscoHardwareStatusMetricAttributeKeyCiscoHardwareComponent, CiscoHardwareStatusMetricAttributeKeyCiscoHardwareName, CiscoHardwareStatusMetricAttributeKeyCiscoHardwareSlot, CiscoHardwareStatusMetricAttributeKeyCiscoHardwareState},
					},
					CiscoHardwareTemperature: CiscoHardwareTemperatureMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoHardwareTemperatureMetricAttributeKey{CiscoHardwareTemperatureMetricAttributeKeyCiscoHardwareName, CiscoHardwareTemperatureMetricAttributeKeyCiscoHardwareSlot, CiscoHardwareTemperatureMetricAttributeKeyCiscoHardwareState},
					},
					CiscoNvePeerStatus: CiscoNvePeerStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoNvePeerStatusMetricAttributeKey{CiscoNvePeerStatusMetricAttributeKeyNetworkPeerAddress, CiscoNvePeerStatusMetricAttributeKeyCiscoNveState},
					},
					CiscoNveVniStatus: CiscoNveVniStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoNveVniStatusMetricAttributeKey{CiscoNveVniStatusMetricAttributeKeyCiscoNveVni, CiscoNveVniStatusMetricAttributeKeyCiscoNveVniType, CiscoNveVniStatusMetricAttributeKeyCiscoNveState},
					},
					CiscoProtocolDropped: CiscoProtocolDroppedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoProtocolDroppedMetricAttributeKey{CiscoProtocolDroppedMetricAttributeKeyCiscoProtocolDropReason, CiscoProtocolDroppedMetricAttributeKeyCiscoProtocolName},
					},
					CiscoProtocolErrors: CiscoProtocolErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoProtocolErrorsMetricAttributeKey{CiscoProtocolErrorsMetricAttributeKeyCiscoProtocolErrorType, CiscoProtocolErrorsMetricAttributeKeyCiscoProtocolName},
					},
					CiscoProtocolPackets: CiscoProtocolPacketsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoProtocolPacketsMetricAttributeKey{CiscoProtocolPacketsMetricAttributeKeyCiscoProtocolMessageType, CiscoProtocolPacketsMetricAttributeKeyCiscoProtocolName, CiscoProtocolPacketsMetricAttributeKeyNetworkIoDirection},
					},
					CiscoQfpDatapathIo: CiscoQfpDatapathIoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoQfpDatapathIoMetricAttributeKey{CiscoQfpDatapathIoMetricAttributeKeyNetworkIoDirection, CiscoQfpDatapathIoMetricAttributeKeyCiscoQfpTrafficClass, CiscoQfpDatapathIoMetricAttributeKeyCiscoCPUWindow},
					},
					CiscoQfpDatapathPacketRate: CiscoQfpDatapathPacketRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoQfpDatapathPacketRateMetricAttributeKey{CiscoQfpDatapathPacketRateMetricAttributeKeyNetworkIoDirection, CiscoQfpDatapathPacketRateMetricAttributeKeyCiscoQfpTrafficClass, CiscoQfpDatapathPacketRateMetricAttributeKeyCiscoCPUWindow},
					},
					CiscoQfpDatapathUtilization: CiscoQfpDatapathUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoQfpDatapathUtilizationMetricAttributeKey{CiscoQfpDatapathUtilizationMetricAttributeKeyCiscoQfpLoadType, CiscoQfpDatapathUtilizationMetricAttributeKeyCiscoCPUWindow},
					},
					CiscoQfpDropBytes: CiscoQfpDropBytesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoQfpDropBytesMetricAttributeKey{CiscoQfpDropBytesMetricAttributeKeyCiscoQfpDropSource, CiscoQfpDropBytesMetricAttributeKeyCiscoForwardingDropReason},
					},
					CiscoQfpDrops: CiscoQfpDropsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoQfpDropsMetricAttributeKey{CiscoQfpDropsMetricAttributeKeyCiscoQfpDropSource, CiscoQfpDropsMetricAttributeKeyCiscoForwardingDropReason},
					},
					CiscoQfpInterfaceDrops: CiscoQfpInterfaceDropsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoQfpInterfaceDropsMetricAttributeKey{CiscoQfpInterfaceDropsMetricAttributeKeyNetworkInterfaceName, CiscoQfpInterfaceDropsMetricAttributeKeyNetworkIoDirection},
					},
					CiscoRoutingNeighborPrefixes: CiscoRoutingNeighborPrefixesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoRoutingNeighborPrefixesMetricAttributeKey{CiscoRoutingNeighborPrefixesMetricAttributeKeyCiscoRoutingProtocol, CiscoRoutingNeighborPrefixesMetricAttributeKeyCiscoRoutingVrf, CiscoRoutingNeighborPrefixesMetricAttributeKeyNetworkPeerAddress, CiscoRoutingNeighborPrefixesMetricAttributeKeyAddressFamily},
					},
					CiscoRoutingNeighborState: CiscoRoutingNeighborStateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoRoutingNeighborStateMetricAttributeKey{CiscoRoutingNeighborStateMetricAttributeKeyCiscoRoutingProtocol, CiscoRoutingNeighborStateMetricAttributeKeyCiscoRoutingVrf, CiscoRoutingNeighborStateMetricAttributeKeyNetworkPeerAddress, CiscoRoutingNeighborStateMetricAttributeKeyCiscoRoutingNeighborState, CiscoRoutingNeighborStateMetricAttributeKeyAddressFamily},
					},
					CiscoRoutingRoutes: CiscoRoutingRoutesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoRoutingRoutesMetricAttributeKey{CiscoRoutingRoutesMetricAttributeKeyCiscoRoutingVrf, CiscoRoutingRoutesMetricAttributeKeyCiscoRouteSource, CiscoRoutingRoutesMetricAttributeKeyAddressFamily},
					},
					CiscoScrapeCommandDuration: CiscoScrapeCommandDurationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []CiscoScrapeCommandDurationMetricAttributeKey{CiscoScrapeCommandDurationMetricAttributeKeyCiscoScrapeCommandFamily, CiscoScrapeCommandDurationMetricAttributeKeyCiscoScrapeCommandOutcome},
					},
					CiscoScrapeCommandErrors: CiscoScrapeCommandErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []CiscoScrapeCommandErrorsMetricAttributeKey{CiscoScrapeCommandErrorsMetricAttributeKeyCiscoScrapeCommandFamily, CiscoScrapeCommandErrorsMetricAttributeKeyCiscoScrapeErrorType},
					},
					CiscoScrapePartialSuccess: CiscoScrapePartialSuccessMetricConfig{
						Enabled: false,
					},
					CiscoSSHReconnects: CiscoSSHReconnectsMetricConfig{
						Enabled: false,
					},
					SystemCPUUtilization: SystemCPUUtilizationMetricConfig{
						Enabled: false,
					},
					SystemMemoryUtilization: SystemMemoryUtilizationMetricConfig{
						Enabled: false,
					},
					SystemUptime: SystemUptimeMetricConfig{
						Enabled: false,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostID:    ResourceAttributeConfig{Enabled: false},
					HostIP:    ResourceAttributeConfig{Enabled: false},
					HostName:  ResourceAttributeConfig{Enabled: false},
					HostType:  ResourceAttributeConfig{Enabled: false},
					HwType:    ResourceAttributeConfig{Enabled: false},
					OsName:    ResourceAttributeConfig{Enabled: false},
					OsVersion: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(CiscoAdjacencyEntriesMetricConfig{}, CiscoArpEntriesMetricConfig{}, CiscoControlPlaneCPUProcessUtilizationMetricConfig{}, CiscoControlPlaneDroppedMetricConfig{}, CiscoControlPlanePacketsMetricConfig{}, CiscoControlPlanePuntRateMetricConfig{}, CiscoDeviceUpMetricConfig{}, CiscoEvpnRoutesMetricConfig{}, CiscoForwardingDropsMetricConfig{}, CiscoForwardingFibEntriesMetricConfig{}, CiscoHardwareStatusMetricConfig{}, CiscoHardwareTemperatureMetricConfig{}, CiscoNvePeerStatusMetricConfig{}, CiscoNveVniStatusMetricConfig{}, CiscoProtocolDroppedMetricConfig{}, CiscoProtocolErrorsMetricConfig{}, CiscoProtocolPacketsMetricConfig{}, CiscoQfpDatapathIoMetricConfig{}, CiscoQfpDatapathPacketRateMetricConfig{}, CiscoQfpDatapathUtilizationMetricConfig{}, CiscoQfpDropBytesMetricConfig{}, CiscoQfpDropsMetricConfig{}, CiscoQfpInterfaceDropsMetricConfig{}, CiscoRoutingNeighborPrefixesMetricConfig{}, CiscoRoutingNeighborStateMetricConfig{}, CiscoRoutingRoutesMetricConfig{}, CiscoScrapeCommandDurationMetricConfig{}, CiscoScrapeCommandErrorsMetricConfig{}, CiscoScrapePartialSuccessMetricConfig{}, CiscoSSHReconnectsMetricConfig{}, SystemCPUUtilizationMetricConfig{}, SystemMemoryUtilizationMetricConfig{}, SystemUptimeMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				HostID:    ResourceAttributeConfig{Enabled: true},
				HostIP:    ResourceAttributeConfig{Enabled: true},
				HostName:  ResourceAttributeConfig{Enabled: true},
				HostType:  ResourceAttributeConfig{Enabled: true},
				HwType:    ResourceAttributeConfig{Enabled: true},
				OsName:    ResourceAttributeConfig{Enabled: true},
				OsVersion: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				HostID:    ResourceAttributeConfig{Enabled: false},
				HostIP:    ResourceAttributeConfig{Enabled: false},
				HostName:  ResourceAttributeConfig{Enabled: false},
				HostType:  ResourceAttributeConfig{Enabled: false},
				HwType:    ResourceAttributeConfig{Enabled: false},
				OsName:    ResourceAttributeConfig{Enabled: false},
				OsVersion: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
